import { getApiBase } from "../api";
import { getSupabase } from "../supabaseClient";

export type TaskStatus = "pending" | "completed";

export type TaskRow = {
  id: string;
  title: string;
  assigned_by: string | null;
  start_time: string;
  end_time: string;
  duration: number;
  urgent: boolean;
  room: string | null;
  status: TaskStatus;
  created_at: string;
  category?: string | null;
  gathering_id?: string | null;
  is_auto_generated?: boolean;
};

export type TaskInsert = {
  title: string;
  assigned_by?: string | null;
  start_time: string;
  end_time: string;
  duration: number;
  urgent?: boolean;
  room?: string | null;
  status?: TaskStatus;
  is_auto_generated?: boolean;
};

export type TaskUpdate = Partial<Omit<TaskInsert, "title">> & { title?: string };

/** Fetches today's tasks from the backend API (GET /api/tasks). */
export async function fetchTasksFromApi(): Promise<TaskRow[]> {
  console.log("[tasks] Fetching tasks...");
  try {
    const data = (await getApiBase("/api/tasks", { cache: "no-store" }) as { ok?: boolean; tasks?: Array<{ id: string; title: string; date: string; startTime: string; endTime: string; durationMinutes?: number; status: string; category?: string; gatheringId?: string | null; isAutoGenerated?: boolean }> });
    const tasks = data?.tasks ?? [];
    return tasks.map((t) => ({
      id: t.id,
      title: t.title,
      assigned_by: null,
      start_time: t.startTime,
      end_time: t.endTime,
      duration: t.durationMinutes ?? 60,
      urgent: false,
      room: null,
      status: t.status as TaskStatus,
      created_at: new Date().toISOString(),
      category: t.category ?? null,
      gathering_id: t.gatheringId ?? null,
      is_auto_generated: t.isAutoGenerated ?? false,
    }));
  } catch (e) {
    console.error("[tasks] fetchTasksFromApi", e);
    throw e;
  }
}

export async function fetchTasks(filters?: { date?: string; status?: TaskStatus }): Promise<TaskRow[]> {
  const supabase = getSupabase();
  let q = supabase.from("tasks").select("*").order("start_time", { ascending: true });
  if (filters?.date) {
    q = q.gte("start_time", `${filters.date}T00:00:00`).lt("start_time", `${filters.date}T23:59:59.999Z`);
  }
  if (filters?.status) q = q.eq("status", filters.status);
  const { data, error } = await q;
  if (error) {
    console.error("[tasks] fetchTasks", error.message, error);
    throw new Error(error.message);
  }
  return (data ?? []) as TaskRow[];
}

export async function createTask(row: TaskInsert): Promise<TaskRow> {
  const supabase = getSupabase();
  const { data, error } = await supabase
    .from("tasks")
    .insert({
      title: row.title,
      assigned_by: row.assigned_by ?? null,
      start_time: row.start_time,
      end_time: row.end_time,
      duration: row.duration ?? 60,
      urgent: row.urgent ?? false,
      room: row.room ?? null,
      status: row.status ?? "pending",
      ...(row.is_auto_generated !== undefined && { is_auto_generated: row.is_auto_generated }),
    })
    .select()
    .single();
  if (error) {
    console.error("[tasks] createTask", error.message, error);
    throw new Error(error.message);
  }
  return data as TaskRow;
}

export async function updateTask(id: string, updates: TaskUpdate): Promise<TaskRow> {
  const supabase = getSupabase();
  const payload: Record<string, unknown> = {};
  if (updates.title !== undefined) payload.title = updates.title;
  if (updates.assigned_by !== undefined) payload.assigned_by = updates.assigned_by;
  if (updates.start_time !== undefined) payload.start_time = updates.start_time;
  if (updates.end_time !== undefined) payload.end_time = updates.end_time;
  if (updates.duration !== undefined) payload.duration = updates.duration;
  if (updates.urgent !== undefined) payload.urgent = updates.urgent;
  if (updates.room !== undefined) payload.room = updates.room;
  if (updates.status !== undefined) payload.status = updates.status;
  const { data, error } = await supabase.from("tasks").update(payload).eq("id", id).select().single();
  if (error) {
    console.error("[tasks] updateTask", error.message, error);
    throw new Error(error.message);
  }
  return data as TaskRow;
}

export async function deleteTask(id: string): Promise<void> {
  const supabase = getSupabase();
  const { error } = await supabase.from("tasks").delete().eq("id", id);
  if (error) {
    console.error("[tasks] deleteTask", error.message, error);
    throw new Error(error.message);
  }
}

export async function completeTask(id: string): Promise<TaskRow> {
  return updateTask(id, { status: "completed" });
}
