"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
} from "@dnd-kit/core";
import { restrictToVerticalAxis } from "@dnd-kit/modifiers";
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
  useSortable,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import GlassCard from "./GlassCard";
import {
  getMergedTasks,
  updateLocalTask,
  removeLocalTask,
  isLocalTask,
} from "./GatheringModal";
import { useRealtimeEvent } from "../../context/RealtimeContext";

const LONG_PRESS_MS = 600;
const TODAY_START_HOUR = 9;
const TODAY_START_MINUTE = 0;

import { getApiBase, getActorHeaders, withActorBody } from "../../lib/api";

const API_BASE = getApiBase();

const taskCardStyle = {
  background: "rgba(255,255,255,0.06)",
  backdropFilter: "blur(18px)",
  WebkitBackdropFilter: "blur(18px)" as const,
  border: "1px solid rgba(255,255,255,0.12)",
  borderRadius: "28px",
  transition: "all 0.3s ease",
};

const glassModalStyle = {
  background: "rgba(18, 24, 38, 0.9)",
  backdropFilter: "blur(24px)",
  WebkitBackdropFilter: "blur(24px)" as const,
  border: "1px solid rgba(255, 255, 255, 0.12)",
  borderRadius: "28px",
  boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(255, 255, 255, 0.06)",
};

type Task = {
  id: string;
  title: string;
  date: string;
  startTime: string;
  endTime?: string;
  durationMinutes?: number;
  status: "pending" | "completed";
  category?: string;
  gatheringId?: string | null;
  isAutoGenerated?: boolean;
  /** Stable display order. Required for correct render order; never sort by startTime. */
  order: number;
};

function formatTimeOnly(iso: string): string {
  return new Date(iso).toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });
}

function formatDateDisplay(dateStr: string): string {
  return new Date(dateStr + "T12:00:00").toLocaleDateString(undefined, {
    weekday: "short",
    month: "short",
    day: "numeric",
  });
}

function timeWindowLabel(iso: string): string {
  const h = new Date(iso).getHours();
  if (h < 12) return "Morning";
  if (h < 17) return "Afternoon";
  return "Evening";
}

function isToday(dateStr: string): boolean {
  const today = new Date().toISOString().slice(0, 10);
  return dateStr === today;
}

/** Only used when loading from API to assign initial order. Do not use for display. */
function sortTodayTasks(tasks: Task[]): Task[] {
  return [...tasks].sort((a, b) => {
    if (a.status === "completed" && b.status !== "completed") return 1;
    if (a.status !== "completed" && b.status === "completed") return -1;
    return new Date(a.startTime).getTime() - new Date(b.startTime).getTime();
  });
}

/** Only sort by order. NO other sorting. Used as single source for render. */
function tasksByOrder(tasks: Task[]): Task[] {
  return [...tasks].sort((a, b) => a.order - b.order);
}

/** recomputeSchedule: assign start/end times sequentially from order; uses each task's durationMinutes. */
function recalculateTimes(incompleteTasks: Task[], dateStr: string): Task[] {
  const todayStart = new Date(`${dateStr}T${String(TODAY_START_HOUR).padStart(2, "0")}:${String(TODAY_START_MINUTE).padStart(2, "0")}:00`);
  const now = new Date();
  let cursor = now > todayStart ? now : todayStart;
  return incompleteTasks.map((t) => {
    const dur = t.durationMinutes ?? 60;
    const startIso = cursor.toISOString();
    cursor = new Date(cursor.getTime() + dur * 60 * 1000);
    const endIso = cursor.toISOString();
    return { ...t, startTime: startIso, endTime: endIso };
  });
}

// Sortable task row (incomplete only)
function SortableTaskRow({
  task,
  isHolding,
  taskCardStyle,
  onPressStart,
  onPressEnd,
  onClick,
  onContextMenu,
  readOnly,
  canReorder,
  simplified,
}: {
  task: Task;
  isHolding: boolean;
  taskCardStyle: React.CSSProperties;
  onPressStart: (e: React.MouseEvent | React.TouchEvent) => void;
  onPressEnd: () => void;
  onClick: (e: React.MouseEvent) => void;
  onContextMenu: (e: React.MouseEvent) => void;
  readOnly?: boolean;
  canReorder?: boolean;
  simplified?: boolean;
}) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: task.id });
  const style: React.CSSProperties = {
    ...taskCardStyle,
    opacity: task.status === "completed" ? 0.4 : 1,
    transform: isDragging ? undefined : isHolding ? "scale(0.97)" : task.status === "completed" ? "scale(0.98)" : undefined,
    boxShadow: isHolding ? "0 0 20px rgba(120,180,255,0.25)" : undefined,
    ...(transform ? { transform: CSS.Transform.toString(transform) } : {}),
    transition,
    maxWidth: "100%",
  };
  return (
    <li ref={setNodeRef} style={style} className="min-w-0">
      <button
        type="button"
        onClick={(e) => onClick(e)}
        onMouseDown={(e) => !readOnly && onPressStart(e)}
        onMouseUp={onPressEnd}
        onMouseLeave={onPressEnd}
        onTouchStart={(e) => !readOnly && onPressStart(e)}
        onTouchEnd={onPressEnd}
        onContextMenu={onContextMenu}
        className={`w-full flex items-center gap-4 px-4 text-left rounded-[28px] border border-white/[0.12] backdrop-blur-[18px] transition-all duration-300 ease-out hover:shadow-[0_0_20px_rgba(120,180,255,0.2)] ${simplified ? "py-4 min-h-[52px]" : "py-3"}`}
        onMouseEnter={(e) => {
          if (task.status !== "completed" && !isHolding) e.currentTarget.style.boxShadow = "0 0 20px rgba(120,180,255,0.2)";
        }}
        onMouseLeave={(e) => { if (!isHolding) e.currentTarget.style.boxShadow = ""; }}
      >
        <span className="shrink-0 w-14 text-xs tabular-nums opacity-70">{formatTimeOnly(task.startTime)}</span>
        <span className={`min-w-0 flex-1 truncate text-[0.875rem] text-white/90 ${task.status === "completed" ? "line-through" : ""}`}>{task.title}</span>
        {task.status !== "completed" && !readOnly && canReorder && (
          <span
            className="drag-handle shrink-0 text-white/40 cursor-grab active:cursor-grabbing select-none"
            style={{ touchAction: "none" }}
            aria-hidden
            {...attributes}
            {...listeners}
          >
            ⋮⋮
          </span>
        )}
      </button>
    </li>
  );
}

// Long-press action modal (Edit, Skip, How to?, Close — no Tick)
function TaskActionModal({
  task,
  onClose,
  onSkip,
  onEdit,
  onHowTo,
  canEditTasks,
}: {
  task: Task;
  onClose: () => void;
  onSkip: () => void;
  onEdit: () => void;
  onHowTo: () => void;
  canEditTasks?: boolean;
}) {
  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center p-4"
      role="dialog"
      aria-modal="true"
      aria-labelledby="task-action-title"
    >
      <div
        className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        onClick={onClose}
        onKeyDown={(e) => e.key === "Escape" && onClose()}
      />
      <div
        className="relative w-full max-w-sm rounded-[28px] p-6 animate-modal-in"
        style={glassModalStyle}
        onClick={(e) => e.stopPropagation()}
      >
        <h3 id="task-action-title" className="text-lg font-semibold text-white/95 mb-4 pr-8">
          {task.title}
        </h3>
        <dl className="space-y-2 text-[0.8125rem] mb-6">
          <div className="flex justify-between gap-4">
            <dt className="text-white/50">Date</dt>
            <dd className="text-white/90">{formatDateDisplay(task.date)}</dd>
          </div>
          <div className="flex justify-between gap-4">
            <dt className="text-white/50">Time</dt>
            <dd className="text-white/90">{formatTimeOnly(task.startTime)}</dd>
          </div>
          <div className="flex justify-between gap-4">
            <dt className="text-white/50">Window</dt>
            <dd className="text-white/90">{timeWindowLabel(task.startTime)}</dd>
          </div>
          <div className="flex justify-between gap-4">
            <dt className="text-white/50">Duration</dt>
            <dd className="text-white/90">{task.durationMinutes ?? 0} min</dd>
          </div>
        </dl>
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => { onSkip(); onClose(); }}
            className="rounded-2xl border border-amber-400/25 bg-amber-500/15 px-4 py-2.5 text-[0.8125rem] font-medium text-amber-300/90 hover:bg-amber-500/20 transition-all"
          >
            Skip
          </button>
          {canEditTasks !== false && (
            <button
              type="button"
              onClick={onEdit}
              className="rounded-2xl border border-white/15 bg-white/10 px-4 py-2.5 text-[0.8125rem] font-medium text-white/90 hover:bg-white/15 transition-all"
            >
              Edit
            </button>
          )}
          <button
            type="button"
            onClick={onHowTo}
            className="rounded-2xl border border-white/15 bg-white/10 px-4 py-2.5 text-[0.8125rem] font-medium text-white/90 hover:bg-white/15 transition-all"
          >
            How to?
          </button>
          <button
            type="button"
            onClick={onClose}
            className="rounded-2xl border border-white/10 bg-white/5 px-4 py-2.5 text-[0.8125rem] font-medium text-white/70 hover:bg-white/10 transition-all ml-auto"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

// Edit task modal (inline)
function EditTaskModal({
  task,
  onClose,
  onSave,
}: {
  task: Task;
  onClose: () => void;
  onSave: (payload: { title: string; date: string; startTime: string; durationMinutes: number }) => void;
}) {
  const [title, setTitle] = useState(task.title);
  const [date, setDate] = useState(task.date);
  const [startTime, setStartTime] = useState(() => {
    const d = new Date(task.startTime);
    return `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
  });
  const [durationMinutes, setDurationMinutes] = useState(task.durationMinutes ?? 60);

  return (
    <div className="fixed inset-0 z-[110] flex items-center justify-center p-4" role="dialog" aria-modal="true">
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={onClose} />
      <div
        className="relative w-full max-w-sm rounded-[28px] p-6 animate-modal-in"
        style={glassModalStyle}
        onClick={(e) => e.stopPropagation()}
      >
        <h3 className="text-lg font-semibold text-white/95 mb-4">Edit task</h3>
        <div className="space-y-3 mb-5">
          <div>
            <label className="block text-[0.6875rem] text-white/50 mb-1 uppercase tracking-wider">Title</label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full rounded-xl px-3.5 py-2.5 text-[0.875rem] text-white/95 border border-white/[0.12] bg-white/[0.06] focus:outline-none focus:border-white/20"
            />
          </div>
          <div>
            <label className="block text-[0.6875rem] text-white/50 mb-1 uppercase tracking-wider">Date</label>
            <input
              type="date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
              className="w-full rounded-xl px-3.5 py-2.5 text-[0.875rem] text-white/95 border border-white/[0.12] bg-white/[0.06] focus:outline-none focus:border-white/20"
            />
          </div>
          <div>
            <label className="block text-[0.6875rem] text-white/50 mb-1 uppercase tracking-wider">Start time</label>
            <input
              type="time"
              value={startTime}
              onChange={(e) => setStartTime(e.target.value)}
              className="w-full rounded-xl px-3.5 py-2.5 text-[0.875rem] text-white/95 border border-white/[0.12] bg-white/[0.06] focus:outline-none focus:border-white/20"
            />
          </div>
          <div>
            <label className="block text-[0.6875rem] text-white/50 mb-1 uppercase tracking-wider">Duration (min)</label>
            <input
              type="number"
              min={5}
              value={durationMinutes}
              onChange={(e) => setDurationMinutes(parseInt(e.target.value, 10) || 15)}
              className="w-full rounded-xl px-3.5 py-2.5 text-[0.875rem] text-white/95 border border-white/[0.12] bg-white/[0.06] focus:outline-none focus:border-white/20"
            />
          </div>
        </div>
        <div className="flex gap-2">
          <button type="button" onClick={onClose} className="flex-1 rounded-2xl border border-white/15 bg-white/5 py-2.5 text-[0.8125rem] font-medium text-white/80 hover:bg-white/10">
            Cancel
          </button>
          <button
            type="button"
            onClick={() => onSave({ title, date, startTime, durationMinutes })}
            className="flex-1 rounded-2xl bg-[rgba(99,179,237,0.2)] border border-[rgba(99,179,237,0.3)] py-2.5 text-[0.8125rem] font-medium text-white/95 hover:bg-[rgba(99,179,237,0.25)]"
          >
            Save
          </button>
        </div>
      </div>
    </div>
  );
}

// How to placeholder modal
function HowToPlaceholderModal({ taskTitle, onClose }: { taskTitle: string; onClose: () => void }) {
  useEffect(() => {
    console.log("How to clicked:", taskTitle);
  }, [taskTitle]);
  return (
    <div className="fixed inset-0 z-[110] flex items-center justify-center p-4" role="dialog" aria-modal="true">
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={onClose} />
      <div
        className="relative w-full max-w-sm rounded-[28px] p-6 animate-modal-in"
        style={glassModalStyle}
        onClick={(e) => e.stopPropagation()}
      >
        <h3 className="text-lg font-semibold text-white/95 mb-3">How to: {taskTitle}</h3>
        <p className="text-[0.8125rem] text-white/60 mb-5">AI instructions coming soon.</p>
        <button
          type="button"
          onClick={onClose}
          className="rounded-2xl border border-white/15 bg-white/5 px-4 py-2.5 text-[0.8125rem] font-medium text-white/80 hover:bg-white/10"
        >
          Close
        </button>
      </div>
    </div>
  );
}

type DailyTasksCardProps = { readOnly?: boolean; canEditTasks?: boolean; canReorder?: boolean; simplified?: boolean };

export default function DailyTasksCard({ readOnly = false, canEditTasks = true, canReorder = true, simplified = false }: DailyTasksCardProps = {}) {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const [editTask, setEditTask] = useState<Task | null>(null);
  const [howToTitle, setHowToTitle] = useState<string | null>(null);
  const [isLongPress, setIsLongPress] = useState(false);
  const [holdingTaskId, setHoldingTaskId] = useState<string | null>(null);
  const pressTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const pendingLongPressTaskRef = useRef<Task | null>(null);
  const tasksRef = useRef<Task[]>(tasks);
  useEffect(() => {
    tasksRef.current = tasks;
  }, [tasks]);

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { delay: 150, tolerance: 5 } }),
    useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates })
  );

  const loadTasks = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(`${API_BASE}/api/tasks`, { cache: "no-store" });
      const data = await res.json().catch(() => null);
      const apiList = res.ok && Array.isArray(data?.tasks) ? data.tasks : [];
      const merged = getMergedTasks(apiList as Task[]);
      const todayOnly = merged.filter((t: Task) => isToday(t.date));
      const sorted = sortTodayTasks(todayOnly).slice(0, 6);
      setTasks(sorted.map((t, i) => ({ ...t, order: i })));
    } catch {
      const merged = getMergedTasks([]);
      const todayOnly = merged.filter((t: Task) => isToday(t.date));
      const sorted = sortTodayTasks(todayOnly).slice(0, 6);
      setTasks(sorted.map((t, i) => ({ ...t, order: i })));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadTasks();
  }, [loadTasks]);

  useEffect(() => {
    const onMidnight = () => loadTasks();
    const onGatheringAdded = () => loadTasks();
    window.addEventListener("midnight-rollover", onMidnight);
    window.addEventListener("gathering-tasks-added", onGatheringAdded);
    return () => {
      window.removeEventListener("midnight-rollover", onMidnight);
      window.removeEventListener("gathering-tasks-added", onGatheringAdded);
    };
  }, [loadTasks]);

  useRealtimeEvent("tasks_updated", loadTasks);

  useEffect(() => {
    return () => {
      if (pressTimerRef.current) clearTimeout(pressTimerRef.current);
    };
  }, []);

  function handlePressStart(task: Task, e: React.MouseEvent | React.TouchEvent) {
    if (readOnly) return;
    if (e.target instanceof HTMLElement && e.target.closest(".drag-handle")) return;
    setIsLongPress(false);
    setHoldingTaskId(task.id);
    pendingLongPressTaskRef.current = task;
    if (pressTimerRef.current) clearTimeout(pressTimerRef.current);
    pressTimerRef.current = setTimeout(() => {
      setIsLongPress(true);
      const t = pendingLongPressTaskRef.current;
      if (t) setSelectedTask(t);
      pressTimerRef.current = null;
    }, LONG_PRESS_MS);
  }

  function handlePressEnd() {
    if (pressTimerRef.current) {
      clearTimeout(pressTimerRef.current);
      pressTimerRef.current = null;
    }
    pendingLongPressTaskRef.current = null;
    setHoldingTaskId(null);
  }

  function handleTaskClick(task: Task, e: React.MouseEvent) {
    if (readOnly) return;
    if (e.target instanceof HTMLElement && e.target.closest(".drag-handle")) return;
    if (isLongPress) return;
    toggleTask(task);
  }

  async function toggleTask(task: Task) {
    const nextStatus = task.status === "completed" ? "pending" : "completed";
    const prevTasks = tasks;
    setTasks((current) => {
      const next = current.map((t) => (t.id === task.id ? { ...t, status: nextStatus } : t));
      if (nextStatus === "completed") {
        const maxOrder = Math.max(-1, ...next.filter((x) => x.status === "completed").map((x) => x.order));
        return next.map((t) => (t.id === task.id ? { ...t, status: "completed" as const, order: maxOrder + 1 } : t));
      }
      const maxOrder = Math.max(-1, ...next.filter((x) => x.status !== "completed").map((x) => x.order));
      return next.map((t) => (t.id === task.id ? { ...t, order: maxOrder + 1 } : t));
    });
    try {
      if (isLocalTask(task.id)) {
        updateLocalTask(task.id, { status: nextStatus });
      } else {
        if (nextStatus === "completed") {
          const res = await fetch(`${API_BASE}/api/tasks/${task.id}/complete`, { method: "PATCH", headers: { ...getActorHeaders() } });
          if (!res.ok) throw new Error("Tick failed");
        } else {
          const res = await fetch(`${API_BASE}/api/tasks/${task.id}`, {
            method: "PATCH",
            headers: { "Content-Type": "application/json", ...getActorHeaders() },
            body: JSON.stringify(withActorBody({ status: "pending" })),
          });
          if (!res.ok) throw new Error("Untick failed");
        }
      }
    } catch {
      setTasks(prevTasks);
      loadTasks();
    }
  }

  function handleSkip(task: Task) {
    if (isLocalTask(task.id)) {
      removeLocalTask(task.id);
    } else {
      fetch(`${API_BASE}/api/tasks/${task.id}`, { method: "DELETE", headers: { ...getActorHeaders() } }).catch(() => {});
    }
    loadTasks();
  }

  async function handleEditSave(
    task: Task,
    payload: { title: string; date: string; startTime: string; durationMinutes: number }
  ) {
    const [h, m] = payload.startTime.split(":").map(Number);
    const startDate = new Date(payload.date);
    startDate.setHours(h, m, 0, 0);
    const startIso = startDate.toISOString();
    const endIso = new Date(startDate.getTime() + payload.durationMinutes * 60 * 1000).toISOString();
    if (isLocalTask(task.id)) {
      updateLocalTask(task.id, {
        title: payload.title,
        date: payload.date,
        startTime: startIso,
        endTime: endIso,
        durationMinutes: payload.durationMinutes,
      });
    } else {
      try {
        await fetch(`${API_BASE}/api/tasks/${task.id}`, {
          method: "PATCH",
          headers: { "Content-Type": "application/json", ...getActorHeaders() },
          body: JSON.stringify(withActorBody({
            title: payload.title,
            date: payload.date,
            startTime: startIso,
            durationMinutes: payload.durationMinutes,
          })),
        });
      } catch {
        // ignore
      }
    }
    setEditTask(null);
    setSelectedTask(null);
    await loadTasks();
  }

  function handleHowTo(task: Task) {
    setHowToTitle(task.title);
    setSelectedTask(null);
    setIsLongPress(false);
  }

  function handleDragStart() {
    document.body.style.overflowX = "hidden";
  }

  /** Reorder by active.id/over.id; reassign order sequentially; recompute times; setTasks with new array ref. */
  async function handleDragEnd(event: DragEndEvent) {
    document.body.style.overflowX = "";
    if (!canReorder) return;
    const { active, over } = event;
    if (!over || String(active.id) === String(over.id)) return;
    const activeId = String(active.id);
    const overId = String(over.id);
    const prev = tasksRef.current;

    const incomplete = prev.filter((t) => t.status !== "completed");
    const oldIndex = incomplete.findIndex((t) => t.id === activeId);
    const newIndex = incomplete.findIndex((t) => t.id === overId);
    if (oldIndex === -1 || newIndex === -1) return;

    const reordered = arrayMove([...incomplete], oldIndex, newIndex);
    const reorderedWithOrder = reordered.map((t, index) => ({ ...t, order: index }));
    const todayStr = new Date().toISOString().slice(0, 10);
    const withNewTimes = recalculateTimes(reorderedWithOrder, todayStr);
    const completed = prev.filter((t) => t.status === "completed");
    const completedWithOrder = completed.map((t, i) => ({ ...t, order: reordered.length + i }));
    const updatedTasks = [...withNewTimes, ...completedWithOrder];

    console.log("REORDER CALLED", updatedTasks);
    setTasks(updatedTasks);
    console.log("STATE AFTER SET", updatedTasks);

    const apiUpdates = withNewTimes.filter((t) => !isLocalTask(t.id)).map((t) => ({ id: t.id, startTime: t.startTime, endTime: t.endTime ?? new Date(new Date(t.startTime).getTime() + (t.durationMinutes ?? 60) * 60000).toISOString() }));
    for (const t of withNewTimes) {
      if (isLocalTask(t.id)) {
        updateLocalTask(t.id, { startTime: t.startTime, endTime: t.endTime });
      }
    }
    if (apiUpdates.length > 0) {
      try {
        const res = await fetch(`${API_BASE}/api/tasks/reorder`, {
          method: "PATCH",
          headers: { "Content-Type": "application/json", ...getActorHeaders() },
          body: JSON.stringify(withActorBody({ tasks: apiUpdates })),
        });
        if (!res.ok) throw new Error("Reorder failed");
      } catch {
        // Do NOT call loadTasks() here — it overwrites state with server order and causes snap-back.
        // Keep the optimistic reorder in state; server may sync on next full load.
      }
    }
  }

  return (
    <GlassCard className="animate-fade-in-up opacity-0 flex flex-col flex-1 min-h-0 overflow-x-hidden" style={{ animationDelay: "0.15s" }}>
      <div className="flex items-center justify-between mb-3 shrink-0">
        <h2 className="text-[1rem] font-medium text-white/90 tracking-tight">
          Today&apos;s Tasks
        </h2>
        {canEditTasks && (
          <Link
            href="/todays-tasks"
            className="text-[0.8125rem] font-medium text-white/60 transition-all duration-300 ease-out hover:scale-[1.02] hover:text-blue-300"
          >
            View all →
          </Link>
        )}
      </div>
      {loading ? (
        <p className="text-[0.8125rem] text-white/45">Loading…</p>
      ) : tasks.length === 0 ? (
        <p className="text-[0.8125rem] text-white/45">No tasks for today. Add some in Today&apos;s Tasks.</p>
      ) : (
        <div className="min-h-0 flex flex-col flex-1 overflow-x-hidden" style={{ minHeight: 0 }}>
          <DndContext
            sensors={sensors}
            collisionDetection={closestCenter}
            modifiers={[restrictToVerticalAxis]}
            onDragStart={handleDragStart}
            onDragEnd={handleDragEnd}
            onDragCancel={() => { document.body.style.overflowX = ""; }}
          >
            <ul
              className="space-y-2.5 overflow-y-auto overflow-x-hidden flex-1 min-h-0 no-scrollbar pb-2 w-full"
            >
              <SortableContext
                items={tasksByOrder(tasks).filter((t) => t.status !== "completed").map((t) => t.id)}
                strategy={verticalListSortingStrategy}
              >
                {tasksByOrder(tasks).map((t) =>
                  t.status !== "completed" ? (
                    <SortableTaskRow
                      key={t.id}
                      task={t}
                      isHolding={holdingTaskId === t.id}
                      taskCardStyle={taskCardStyle}
                      onPressStart={(e) => handlePressStart(t, e)}
                      onPressEnd={handlePressEnd}
                      onClick={(e) => handleTaskClick(t, e)}
                      onContextMenu={(e) => e.preventDefault()}
                      readOnly={readOnly}
                      canReorder={canReorder}
                      simplified={simplified}
                    />
                  ) : (
                    <li key={t.id}>
                      <button
                        type="button"
                        onClick={(e) => handleTaskClick(t, e)}
                        onMouseDown={(e) => !readOnly && handlePressStart(t, e)}
                        onMouseUp={handlePressEnd}
                        onMouseLeave={handlePressEnd}
                        onTouchStart={(e) => !readOnly && handlePressStart(t, e)}
                        onTouchEnd={handlePressEnd}
                        onContextMenu={(e) => e.preventDefault()}
                        className={`w-full flex items-center gap-4 px-4 py-3 text-left rounded-[28px] border border-white/[0.12] backdrop-blur-[18px] transition-all duration-300 ease-out ${simplified ? "min-h-[52px] py-4" : ""}`}
                        style={{
                          ...taskCardStyle,
                          opacity: 0.4,
                          transform: "scale(0.98)",
                        }}
                      >
                        <span className="shrink-0 w-14 text-xs tabular-nums opacity-70">{formatTimeOnly(t.startTime)}</span>
                        <span className="min-w-0 flex-1 truncate text-[0.875rem] text-white/90 line-through">{t.title}</span>
                      </button>
                    </li>
                  )
                )}
              </SortableContext>
            </ul>
          </DndContext>
        </div>
      )}

      {selectedTask && (
        <TaskActionModal
          task={selectedTask}
          onClose={() => { setSelectedTask(null); setIsLongPress(false); }}
          onSkip={() => handleSkip(selectedTask)}
          onEdit={() => { setEditTask(selectedTask); setSelectedTask(null); setIsLongPress(false); }}
          onHowTo={() => handleHowTo(selectedTask)}
          canEditTasks={canEditTasks}
        />
      )}
      {editTask && (
        <EditTaskModal
          task={editTask}
          onClose={() => { setEditTask(null); setSelectedTask(null); }}
          onSave={(payload) => handleEditSave(editTask, payload)}
        />
      )}
      {howToTitle && (
        <HowToPlaceholderModal taskTitle={howToTitle} onClose={() => setHowToTitle(null)} />
      )}
    </GlassCard>
  );
}
