"use client";

import { useState, useCallback } from "react";

const LOCAL_TASKS_KEY = "smarthub_local_tasks";

const GATHERING_TYPES = [
  { value: "lunch", label: "Lunch" },
  { value: "dinner", label: "Dinner" },
  { value: "casual_evening", label: "Casual evening" },
  { value: "other", label: "Other" },
] as const;

const glassModalStyle = {
  background: "rgba(18, 24, 38, 0.85)",
  backdropFilter: "blur(24px)",
  WebkitBackdropFilter: "blur(24px)" as const,
  border: "1px solid rgba(255, 255, 255, 0.1)",
  boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(255, 255, 255, 0.05)",
};

export type GeneratedTask = {
  id: string;
  title: string;
  date: string;
  startTime: string;
  endTime: string;
  durationMinutes: number;
  status: "pending";
  category?: string;
  isAutoGenerated?: boolean;
};

function nextId(): string {
  return typeof crypto !== "undefined" && crypto.randomUUID
    ? crypto.randomUUID()
    : `gathering-${Date.now()}-${Math.random().toString(36).slice(2, 11)}`;
}

function toISODate(dateStr: string, hour: number, minute: number): string {
  const d = new Date(`${dateStr}T00:00:00`);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function addMinutes(iso: string, minutes: number): string {
  const d = new Date(iso);
  d.setMinutes(d.getMinutes() + minutes);
  return d.toISOString();
}

/** Generate gathering tasks with deterministic scheduling. No backend/AI. */
function generateGatheringTasks(params: {
  gatheringType: string;
  guestCount: number;
  date: string;
  time: string;
}): GeneratedTask[] {
  const { gatheringType, date: eventDateStr, time: eventTimeStr } = params;
  const today = new Date();
  const todayStr = today.toISOString().slice(0, 10);
  const eventDate = new Date(`${eventDateStr}T12:00:00`);
  const todayStart = new Date(todayStr + "T00:00:00");
  const daysUntil = Math.round((eventDate.getTime() - todayStart.getTime()) / (24 * 60 * 60 * 1000));
  const isLunch = gatheringType === "lunch";
  const gateTime = isLunch ? { hour: 14, minute: 0 } : { hour: 19, minute: 0 };

  const ROOMS_45 = [
    "Mariam's Room",
    "Winklevoss' Room",
    "Master Bedroom",
    "Kitchen",
  ];
  const ROOMS_60 = ["Dining Room", "TV Room", "Outdoor Seating Area"];
  const DRIVEWAY = { title: "Driveway", duration: 180 };
  const PREP_TASKS = [
    { title: "Buy ingredients for cooking", duration: 60 },
    { title: "Check toilet supplies", duration: 20 },
    { title: "Buy plastic water bottles & soft drinks", duration: 45 },
    { title: "Move buffet table", duration: 45 },
    { title: "Prepare nuts & snacks", duration: 45 },
    { title: "Prepare tea", duration: 30 },
    { title: "Prepare Arabic coffee", duration: 30 },
  ];
  const GATE_TASK = { title: "Keep gate open", duration: 5 };

  const tasks: GeneratedTask[] = [];
  const SCHEDULE_START_HOUR = 9;
  const SCHEDULE_START_MINUTE = 0;

  function placeOnDay(dateStr: string, taskList: { title: string; duration: number }[]): void {
    let cursor = new Date(`${dateStr}T${String(SCHEDULE_START_HOUR).padStart(2, "0")}:${String(SCHEDULE_START_MINUTE).padStart(2, "0")}:00`);
    for (const t of taskList) {
      const startIso = cursor.toISOString();
      const endIso = addMinutes(startIso, t.duration);
      tasks.push({
        id: nextId(),
        title: t.title,
        date: dateStr,
        startTime: startIso,
        endTime: endIso,
        durationMinutes: t.duration,
        status: "pending",
        isAutoGenerated: true,
      });
      cursor = new Date(endIso);
    }
  }

  if (daysUntil === 1) {
    const heavyToday = [
      ...ROOMS_45.map((title) => ({ title, duration: 45 })),
      ...ROOMS_60.map((title) => ({ title, duration: 60 })),
      { title: "Buy ingredients for cooking", duration: 60 },
      { title: "Check toilet supplies", duration: 20 },
      { title: "Buy plastic water bottles & soft drinks", duration: 45 },
      { title: "Move buffet table", duration: 45 },
    ];
    placeOnDay(todayStr, heavyToday);

    const lightOnEventDay = [
      { title: "Prepare nuts & snacks", duration: 45 },
      { title: "Prepare tea", duration: 30 },
      { title: "Prepare Arabic coffee", duration: 30 },
    ];
    placeOnDay(eventDateStr, lightOnEventDay);

    const gateStart = toISODate(eventDateStr, gateTime.hour, gateTime.minute);
    tasks.push({
      id: nextId(),
      title: GATE_TASK.title,
      date: eventDateStr,
      startTime: gateStart,
      endTime: addMinutes(gateStart, GATE_TASK.duration),
      durationMinutes: GATE_TASK.duration,
      status: "pending",
      isAutoGenerated: true,
    });
  } else if (daysUntil >= 2) {
    const roomTasks = [
      ...ROOMS_45.map((title) => ({ title, duration: 45 })),
      ...ROOMS_60.map((title) => ({ title, duration: 60 })),
    ];
    if (daysUntil >= 7) {
      roomTasks.push({ title: DRIVEWAY.title, duration: DRIVEWAY.duration });
    }
    const prepTasks = [...PREP_TASKS];
    const allPrepped = [...roomTasks, ...prepTasks];
    const daysForPrepped: string[] = [];
    for (let d = 0; d < daysUntil; d++) {
      const d2 = new Date(today);
      d2.setDate(d2.getDate() + d);
      daysForPrepped.push(d2.toISOString().slice(0, 10));
    }
    const chunks: { title: string; duration: number }[][] = daysForPrepped.map(() => []);
    allPrepped.forEach((t, i) => {
      const dayIdx = i % daysForPrepped.length;
      chunks[dayIdx].push(t);
    });
    chunks.forEach((chunk, i) => {
      if (chunk.length) placeOnDay(daysForPrepped[i], chunk);
    });

    const gateStart = toISODate(eventDateStr, gateTime.hour, gateTime.minute);
    tasks.push({
      id: nextId(),
      title: GATE_TASK.title,
      date: eventDateStr,
      startTime: gateStart,
      endTime: addMinutes(gateStart, GATE_TASK.duration),
      durationMinutes: GATE_TASK.duration,
      status: "pending",
      isAutoGenerated: true,
    });
  } else {
    const roomTasks = [
      ...ROOMS_45.map((title) => ({ title, duration: 45 })),
      ...ROOMS_60.map((title) => ({ title, duration: 60 })),
      ...PREP_TASKS,
    ];
    placeOnDay(todayStr, roomTasks);
    const gateStart = toISODate(eventDateStr, gateTime.hour, gateTime.minute);
    tasks.push({
      id: nextId(),
      title: GATE_TASK.title,
      date: eventDateStr,
      startTime: gateStart,
      endTime: addMinutes(gateStart, GATE_TASK.duration),
      durationMinutes: GATE_TASK.duration,
      status: "pending",
      isAutoGenerated: true,
    });
  }

  tasks.sort((a, b) => {
    if (a.date !== b.date) return a.date.localeCompare(b.date);
    return new Date(a.startTime).getTime() - new Date(b.startTime).getTime();
  });
  return tasks;
}

function loadLocalTasks(): GeneratedTask[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(LOCAL_TASKS_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function saveLocalTasks(newTasks: GeneratedTask[]): void {
  if (typeof window === "undefined") return;
  try {
    const existing = loadLocalTasks();
    const byId = new Map(existing.map((t) => [t.id, t]));
    for (const t of newTasks) byId.set(t.id, t);
    const merged = Array.from(byId.values()).sort((a, b) => {
      if (a.date !== b.date) return a.date.localeCompare(b.date);
      return new Date(a.startTime).getTime() - new Date(b.startTime).getTime();
    });
    localStorage.setItem(LOCAL_TASKS_KEY, JSON.stringify(merged));
  } catch {
    // ignore
  }
}

export type TaskLike = {
  id: string;
  title: string;
  date: string;
  startTime: string;
  endTime?: string;
  durationMinutes?: number;
  status: string;
  [key: string]: unknown;
};

export function getMergedTasks(apiTasks: TaskLike[]): TaskLike[] {
  const local = loadLocalTasks();
  const apiIds = new Set(apiTasks.map((t) => t.id));
  const combined: TaskLike[] = [...apiTasks];
  for (const t of local) {
    if (!apiIds.has(t.id)) combined.push(t);
  }
  combined.sort((a, b) => {
    if (a.status === "completed" && b.status !== "completed") return 1;
    if (a.status !== "completed" && b.status === "completed") return -1;
    if (a.date !== b.date) return a.date.localeCompare(b.date);
    return new Date(a.startTime).getTime() - new Date(b.startTime).getTime();
  });
  return combined;
}

export function updateLocalTask(
  id: string,
  payload: { status?: string; title?: string; date?: string; startTime?: string; endTime?: string; durationMinutes?: number }
): void {
  const tasks = loadLocalTasks();
  const idx = tasks.findIndex((t) => t.id === id);
  if (idx === -1) return;
  const next = { ...tasks[idx], ...payload };
  tasks[idx] = next;
  saveLocalTasks(tasks);
}

export function removeLocalTask(id: string): void {
  saveLocalTasks(loadLocalTasks().filter((t) => t.id !== id));
}

export function isLocalTask(id: string): boolean {
  return id.startsWith("gathering-");
}

type Props = {
  isOpen: boolean;
  onClose: () => void;
  onSuccess?: () => void;
};

export default function GatheringModal({ isOpen, onClose, onSuccess }: Props) {
  const [gatheringType, setGatheringType] = useState<string>("dinner");
  const [guestCount, setGuestCount] = useState<string>("4");
  const [date, setDate] = useState(() => {
    const d = new Date();
    d.setDate(d.getDate() + 1);
    return d.toISOString().slice(0, 10);
  });
  const [time, setTime] = useState("18:00");
  const [submitting, setSubmitting] = useState(false);
  const [toast, setToast] = useState<string | null>(null);

  const showToast = useCallback((message: string) => {
    setToast(message);
    const t = setTimeout(() => setToast(null), 3000);
    return () => clearTimeout(t);
  }, []);

  if (!isOpen) return null;

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSubmitting(true);
    try {
      const generated = generateGatheringTasks({
        gatheringType,
        guestCount: parseInt(guestCount, 10) || 0,
        date,
        time,
      });
      saveLocalTasks(loadLocalTasks().concat(generated));
      showToast("Tasks generated successfully");
      onSuccess?.();
      if (typeof window !== "undefined") {
        window.dispatchEvent(new CustomEvent("gathering-tasks-added"));
      }
      onClose();
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center p-4"
      role="dialog"
      aria-modal="true"
      aria-labelledby="gathering-modal-title"
    >
      <div
        className="absolute inset-0 bg-black/40 backdrop-blur-sm"
        onClick={onClose}
        onKeyDown={(e) => e.key === "Escape" && onClose()}
      />
      <div
        className="relative w-full max-w-md rounded-2xl p-6 animate-fade-in-up"
        style={glassModalStyle}
        onClick={(e) => e.stopPropagation()}
      >
        <h2 id="gathering-modal-title" className="text-lg font-semibold text-white/95 tracking-tight mb-5">
          Gathering Mode
        </h2>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-[0.6875rem] text-white/50 mb-1.5 uppercase tracking-wider">
              What type of gathering?
            </label>
            <select
              value={gatheringType}
              onChange={(e) => setGatheringType(e.target.value)}
              className="w-full rounded-xl px-3.5 py-2.5 text-[0.875rem] text-white/95 border border-white/[0.08] bg-white/[0.06] backdrop-blur-[12px] focus:outline-none focus:border-white/15 focus:ring-2 focus:ring-[rgba(99,179,237,0.2)]"
            >
              {GATHERING_TYPES.map((opt) => (
                <option key={opt.value} value={opt.value} className="bg-[#0f172a] text-white">
                  {opt.label}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-[0.6875rem] text-white/50 mb-1.5 uppercase tracking-wider">
              How many guests?
            </label>
            <input
              type="number"
              min={0}
              value={guestCount}
              onChange={(e) => setGuestCount(e.target.value)}
              className="w-full rounded-xl px-3.5 py-2.5 text-[0.875rem] text-white/95 border border-white/[0.08] bg-white/[0.06] backdrop-blur-[12px] focus:outline-none focus:border-white/15 focus:ring-2 focus:ring-[rgba(99,179,237,0.2)]"
            />
          </div>
          <div>
            <label className="block text-[0.6875rem] text-white/50 mb-1.5 uppercase tracking-wider">
              Which day is the gathering?
            </label>
            <input
              type="date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
              className="w-full rounded-xl px-3.5 py-2.5 text-[0.875rem] text-white/95 border border-white/[0.08] bg-white/[0.06] backdrop-blur-[12px] focus:outline-none focus:border-white/15 focus:ring-2 focus:ring-[rgba(99,179,237,0.2)]"
            />
          </div>
          <div>
            <label className="block text-[0.6875rem] text-white/50 mb-1.5 uppercase tracking-wider">
              Time of gathering?
            </label>
            <input
              type="time"
              value={time}
              onChange={(e) => setTime(e.target.value)}
              className="w-full rounded-xl px-3.5 py-2.5 text-[0.875rem] text-white/95 border border-white/[0.08] bg-white/[0.06] backdrop-blur-[12px] focus:outline-none focus:border-white/15 focus:ring-2 focus:ring-[rgba(99,179,237,0.2)]"
            />
          </div>
          <div className="flex gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 rounded-xl border border-white/15 bg-white/5 px-4 py-2.5 text-[0.875rem] font-medium text-white/80 hover:bg-white/10 transition-all"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={submitting}
              className="flex-1 rounded-xl bg-[rgba(99,179,237,0.2)] border border-[rgba(99,179,237,0.3)] px-4 py-2.5 text-[0.875rem] font-medium text-white/95 hover:bg-[rgba(99,179,237,0.25)] transition-all disabled:opacity-50"
            >
              {submitting ? "Creating…" : "Generate Tasks"}
            </button>
          </div>
        </form>
      </div>
      {toast && (
        <div
          className="fixed bottom-6 left-1/2 -translate-x-1/2 z-[101] rounded-xl px-5 py-3 text-[0.875rem] font-medium text-white/95 animate-fade-in"
          style={{
            background: "rgba(34, 197, 94, 0.9)",
            backdropFilter: "blur(12px)",
            border: "1px solid rgba(255,255,255,0.15)",
            boxShadow: "0 10px 40px rgba(0,0,0,0.2)",
          }}
        >
          {toast}
        </div>
      )}
    </div>
  );
}
