"use client";

import { useState } from "react";
import { getSupabaseClient } from "@/lib/supabaseClient";
import * as tasksService from "@/lib/services/tasks";

const LOCAL_TASKS_KEY = "smarthub_local_tasks";

const GATHERING_TYPES = [
  { value: "lunch", label: "Lunch" },
  { value: "dinner", label: "Dinner" },
  { value: "casual_evening", label: "Casual evening" },
  { value: "other", label: "Other" },
] as const;

const glassModalStyle = {
  background: "rgba(18, 24, 38, 0.85)",
  backdropFilter: "blur(24px)",
  WebkitBackdropFilter: "blur(24px)" as const,
  border: "1px solid rgba(255, 255, 255, 0.1)",
  boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(255, 255, 255, 0.05)",
};

export type GeneratedTask = {
  id: string;
  title: string;
  date: string;
  startTime: string;
  endTime: string;
  durationMinutes: number;
  status: "pending";
  category?: string;
  isAutoGenerated?: boolean;
};

function nextId(): string {
  return typeof crypto !== "undefined" && crypto.randomUUID
    ? crypto.randomUUID()
    : `gathering-${Date.now()}-${Math.random().toString(36).slice(2, 11)}`;
}

function toISODate(dateStr: string, hour: number, minute: number): string {
  const d = new Date(`${dateStr}T00:00:00`);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function addMinutes(iso: string, minutes: number): string {
  const d = new Date(iso);
  d.setMinutes(d.getMinutes() + minutes);
  return d.toISOString();
}

/** Generate gathering tasks with deterministic scheduling. No backend/AI. */
function generateGatheringTasks(params: {
  gatheringType: string;
  guestCount: number;
  date: string;
  time: string;
}): GeneratedTask[] {
  const { gatheringType, date: eventDateStr, time: eventTimeStr } = params;
  const today = new Date();
  const todayStr = today.toISOString().slice(0, 10);
  const eventDate = new Date(`${eventDateStr}T12:00:00`);
  const todayStart = new Date(todayStr + "T00:00:00");
  const daysUntil = Math.round((eventDate.getTime() - todayStart.getTime()) / (24 * 60 * 60 * 1000));
  const isLunch = gatheringType === "lunch";
  const gateTime = isLunch ? { hour: 14, minute: 0 } : { hour: 19, minute: 0 };

  const ROOMS_45 = [
    "Mariam's Room",
    "Winklevoss' Room",
    "Master Bedroom",
    "Kitchen",
  ];
  const ROOMS_60 = ["Dining Room", "TV Room", "Outdoor Seating Area"];
  const DRIVEWAY = { title: "Driveway", duration: 180 };
  const PREP_TASKS = [
    { title: "Buy ingredients for cooking", duration: 60 },
    { title: "Check toilet supplies", duration: 20 },
    { title: "Buy plastic water bottles & soft drinks", duration: 45 },
    { title: "Move buffet table", duration: 45 },
    { title: "Prepare nuts & snacks", duration: 45 },
    { title: "Prepare tea", duration: 30 },
    { title: "Prepare Arabic coffee", duration: 30 },
  ];
  const GATE_TASK = { title: "Keep gate open", duration: 5 };

  const tasks: GeneratedTask[] = [];
  const SCHEDULE_START_HOUR = 9;
  const SCHEDULE_START_MINUTE = 0;

  function placeOnDay(dateStr: string, taskList: { title: string; duration: number }[]): void {
    let cursor = new Date(`${dateStr}T${String(SCHEDULE_START_HOUR).padStart(2, "0")}:${String(SCHEDULE_START_MINUTE).padStart(2, "0")}:00`);
    for (const t of taskList) {
      const startIso = cursor.toISOString();
      const endIso = addMinutes(startIso, t.duration);
      tasks.push({
        id: nextId(),
        title: t.title,
        date: dateStr,
        startTime: startIso,
        endTime: endIso,
        durationMinutes: t.duration,
        status: "pending",
        isAutoGenerated: true,
      });
      cursor = new Date(endIso);
    }
  }

  if (daysUntil === 1) {
    const heavyToday = [
      ...ROOMS_45.map((title) => ({ title, duration: 45 })),
      ...ROOMS_60.map((title) => ({ title, duration: 60 })),
      { title: "Buy ingredients for cooking", duration: 60 },
      { title: "Check toilet supplies", duration: 20 },
      { title: "Buy plastic water bottles & soft drinks", duration: 45 },
      { title: "Move buffet table", duration: 45 },
    ];
    placeOnDay(todayStr, heavyToday);

    const lightOnEventDay = [
      { title: "Prepare nuts & snacks", duration: 45 },
      { title: "Prepare tea", duration: 30 },
      { title: "Prepare Arabic coffee", duration: 30 },
    ];
    placeOnDay(eventDateStr, lightOnEventDay);

    const gateStart = toISODate(eventDateStr, gateTime.hour, gateTime.minute);
    tasks.push({
      id: nextId(),
      title: GATE_TASK.title,
      date: eventDateStr,
      startTime: gateStart,
      endTime: addMinutes(gateStart, GATE_TASK.duration),
      durationMinutes: GATE_TASK.duration,
      status: "pending",
      isAutoGenerated: true,
    });
  } else if (daysUntil >= 2) {
    const roomTasks = [
      ...ROOMS_45.map((title) => ({ title, duration: 45 })),
      ...ROOMS_60.map((title) => ({ title, duration: 60 })),
    ];
    if (daysUntil >= 7) {
      roomTasks.push({ title: DRIVEWAY.title, duration: DRIVEWAY.duration });
    }
    const prepTasks = [...PREP_TASKS];
    const allPrepped = [...roomTasks, ...prepTasks];
    const daysForPrepped: string[] = [];
    for (let d = 0; d < daysUntil; d++) {
      const d2 = new Date(today);
      d2.setDate(d2.getDate() + d);
      daysForPrepped.push(d2.toISOString().slice(0, 10));
    }
    const chunks: { title: string; duration: number }[][] = daysForPrepped.map(() => []);
    allPrepped.forEach((t, i) => {
      const dayIdx = i % daysForPrepped.length;
      chunks[dayIdx].push(t);
    });
    chunks.forEach((chunk, i) => {
      if (chunk.length) placeOnDay(daysForPrepped[i], chunk);
    });

    const gateStart = toISODate(eventDateStr, gateTime.hour, gateTime.minute);
    tasks.push({
      id: nextId(),
      title: GATE_TASK.title,
      date: eventDateStr,
      startTime: gateStart,
      endTime: addMinutes(gateStart, GATE_TASK.duration),
      durationMinutes: GATE_TASK.duration,
      status: "pending",
      isAutoGenerated: true,
    });
  } else {
    const roomTasks = [
      ...ROOMS_45.map((title) => ({ title, duration: 45 })),
      ...ROOMS_60.map((title) => ({ title, duration: 60 })),
      ...PREP_TASKS,
    ];
    placeOnDay(todayStr, roomTasks);
    const gateStart = toISODate(eventDateStr, gateTime.hour, gateTime.minute);
    tasks.push({
      id: nextId(),
      title: GATE_TASK.title,
      date: eventDateStr,
      startTime: gateStart,
      endTime: addMinutes(gateStart, GATE_TASK.duration),
      durationMinutes: GATE_TASK.duration,
      status: "pending",
      isAutoGenerated: true,
    });
  }

  tasks.sort((a, b) => {
    if (a.date !== b.date) return a.date.localeCompare(b.date);
    return new Date(a.startTime).getTime() - new Date(b.startTime).getTime();
  });
  return tasks;
}

function loadLocalTasks(): GeneratedTask[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(LOCAL_TASKS_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function saveLocalTasks(newTasks: GeneratedTask[]): void {
  if (typeof window === "undefined") return;
  try {
    const existing = loadLocalTasks();
    const byId = new Map(existing.map((t) => [t.id, t]));
    for (const t of newTasks) byId.set(t.id, t);
    const merged = Array.from(byId.values()).sort((a, b) => {
      if (a.date !== b.date) return a.date.localeCompare(b.date);
      return new Date(a.startTime).getTime() - new Date(b.startTime).getTime();
    });
    localStorage.setItem(LOCAL_TASKS_KEY, JSON.stringify(merged));
  } catch {
    // ignore
  }
}

export type TaskLike = {
  id: string;
  title: string;
  date: string;
  startTime: string;
  endTime?: string;
  durationMinutes?: number;
  status: string;
  [key: string]: unknown;
};

export function getMergedTasks(apiTasks: TaskLike[]): TaskLike[] {
  const local = loadLocalTasks();
  const apiIds = new Set(apiTasks.map((t) => t.id));
  const combined: TaskLike[] = [...apiTasks];
  for (const t of local) {
    if (!apiIds.has(t.id)) combined.push(t);
  }
  combined.sort((a, b) => {
    if (a.status === "completed" && b.status !== "completed") return 1;
    if (a.status !== "completed" && b.status === "completed") return -1;
    if (a.date !== b.date) return a.date.localeCompare(b.date);
    return new Date(a.startTime).getTime() - new Date(b.startTime).getTime();
  });
  return combined;
}

export function updateLocalTask(
  id: string,
  payload: { status?: string; title?: string; date?: string; startTime?: string; endTime?: string; durationMinutes?: number }
): void {
  const tasks = loadLocalTasks();
  const idx = tasks.findIndex((t) => t.id === id);
  if (idx === -1) return;
  const next: GeneratedTask = {
    ...tasks[idx],
    ...payload,
    status: (payload.status ?? tasks[idx].status) as GeneratedTask["status"],
  };
  const nextTasks = [...tasks];
  nextTasks[idx] = next;
  saveLocalTasks(nextTasks);
}

export function removeLocalTask(id: string): void {
  saveLocalTasks(loadLocalTasks().filter((t) => t.id !== id));
}

export function isLocalTask(id: string): boolean {
  return id.startsWith("gathering-");
}

type Props = {
  open: boolean;
  onClose: () => void;
};

const STEPS = [
  {
    question: "How many guests are coming?",
    options: ["2-4", "5-8", "9-15", "15+"],
  },
  {
    question: "What type of gathering?",
    options: ["Dinner", "Coffee", "Party", "Family"],
  },
  {
    question: "Should the house prepare automatically?",
    options: ["Lights", "Music", "Cleaning", "All"],
  },
] as const;

function guestOptionToCount(opt: string): number {
  if (opt === "2-4") return 3;
  if (opt === "5-8") return 6;
  if (opt === "9-15") return 12;
  return 20;
}

function typeOptionToGatheringType(opt: string): string {
  if (opt === "Dinner") return "dinner";
  if (opt === "Coffee") return "casual_evening";
  if (opt === "Party") return "other";
  return "lunch";
}

export default function GatheringModal({ open, onClose }: Props) {
  const [step, setStep] = useState(0);
  const [selectedGuests, setSelectedGuests] = useState<string | null>(null);
  const [selectedType, setSelectedType] = useState<string | null>(null);
  const [selectedPrepare, setSelectedPrepare] = useState<string | null>(null);

  if (!open) return null;

  function handleOptionSelect(option: string) {
    if (step === 0) setSelectedGuests(option);
    if (step === 1) setSelectedType(option);
    if (step === 2) setSelectedPrepare(option);
    setStep((s) => s + 1);
  }

  async function handleDone() {
    const date = (() => {
      const d = new Date();
      d.setDate(d.getDate() + 1);
      return d.toISOString().slice(0, 10);
    })();
    const time = "18:00";
    const guestCount = selectedGuests ? guestOptionToCount(selectedGuests) : 4;
    const gatheringType = selectedType ? typeOptionToGatheringType(selectedType) : "dinner";
    const generated = generateGatheringTasks({
      gatheringType,
      guestCount,
      date,
      time,
    });
    if (getSupabaseClient()) {
      try {
        for (const t of generated) {
          await tasksService.createTask({
            title: t.title,
            start_time: t.startTime,
            end_time: t.endTime,
            duration: t.durationMinutes,
            is_auto_generated: t.isAutoGenerated,
          });
        }
      } catch {
        // leave modal open or show error
      }
    } else {
      saveLocalTasks(loadLocalTasks().concat(generated));
    }
    if (typeof window !== "undefined") {
      window.dispatchEvent(new CustomEvent("gathering-tasks-added"));
    }
    onClose();
  }

  if (step >= STEPS.length) {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm">
        <div
          className="w-[480px] max-w-[90vw] rounded-3xl bg-[#0f172a] border border-white/10 p-6 shadow-2xl"
          onClick={(e) => e.stopPropagation()}
        >
          <h2 className="text-xl font-semibold text-white mb-4">Preparing the house…</h2>
          <p className="text-slate-400">Tasks will be created automatically.</p>
          <button
            type="button"
            onClick={handleDone}
            className="mt-6 bg-blue-500 rounded-xl px-5 py-2 text-white font-medium transition active:scale-[0.97]"
          >
            Done
          </button>
        </div>
      </div>
    );
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-labelledby="gathering-modal-title"
    >
      <div
        className="absolute inset-0"
        onClick={onClose}
        onKeyDown={(e) => e.key === "Escape" && onClose()}
        role="button"
        tabIndex={0}
        aria-label="Close"
      />
      <div
        id="gathering-modal-title"
        className="relative w-[480px] max-w-[90vw] rounded-3xl bg-[#0f172a] border border-white/10 p-6 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <h2 className="text-xl font-semibold text-white mb-6">
          {STEPS[step].question}
        </h2>
        <div className="grid gap-3">
          {STEPS[step].options.map((option) => (
            <button
              key={option}
              type="button"
              onClick={() => handleOptionSelect(option)}
              className="rounded-2xl bg-slate-800 hover:bg-slate-700 py-4 px-5 text-left text-white transition active:scale-[0.97]"
            >
              {option}
            </button>
          ))}
        </div>
        {step > 0 && (
          <button
            type="button"
            onClick={() => setStep((s) => s - 1)}
            className="mt-6 text-sm text-slate-400 hover:text-white transition"
          >
            Back
          </button>
        )}
      </div>
    </div>
  );
}
