import "dotenv/config";
import Fastify from "fastify";
import pg from "pg";
import cors from "@fastify/cors";
import path from "path";
import { fileURLToPath } from "url";
import fastifyStatic from "@fastify/static";
import { getDevices, getDeviceStatus, setDeviceSwitch, turnOffIfOn, listDevices } from "./tuyaClient.js";
import { generateHowToAnswer } from "./openaiClient.js";
import * as dailyTasksDb from "./lib/dailyTasksDb.js";

// ---- Startup validation: required ENV (exit if missing) ----
const requiredTuyaEnv = ["TUYA_ACCESS_ID", "TUYA_ACCESS_SECRET", "TUYA_ENDPOINT", "TUYA_DEVICE_IDS"];
const missing = requiredTuyaEnv.filter((k) => !process.env[k] || String(process.env[k]).trim() === "");
if (missing.length > 0) {
  console.error("Missing required ENV:", missing.join(", "));
  process.exit(1);
}
console.log("ENV loaded");
console.log("Tuya client initialized ✅");

// ---- Helpers: consistent JSON { ok, data?, error? }, never expose stack ----
function safeErrorMessage(e) {
  if (e == null) return "Server error";
  const msg = e instanceof Error ? e.message : String(e);
  return (msg && msg.slice(0, 200)) || "Server error";
}

function sendError(reply, code, error) {
  return reply.code(code).send({ ok: false, error: String(error).slice(0, 200) });
}

const fastify = Fastify({ logger: true });

// ---- Structured logging: route hits ----
fastify.addHook("onRequest", async (request, reply) => {
  request.log.info({ method: request.method, url: request.url }, "route hit");
});

await fastify.register(cors, {
  origin: ["http://localhost:3000", "http://127.0.0.1:3000"],
  methods: ["GET", "POST", "PATCH", "PUT", "DELETE", "OPTIONS"],
});

const db = new pg.Pool({
  host: "localhost",
  user: "postgres",
  password: "postgres",
  database: "smarthub",
  port: 5432,
});

// Daily reset (midnight): clear completed/ticked items
let lastCleanupDay = new Date().toDateString();
setInterval(async () => {
  try {
    const now = new Date();
    const day = now.toDateString();
    if (day === lastCleanupDay) return;
    lastCleanupDay = day;

    // Reset recurring tasks (so they re-appear next day)
    await db.query("UPDATE tasks SET is_done = false WHERE is_done = true");

    // Remove acknowledged urgent tasks (so they disappear after midnight)
    await db.query("DELETE FROM urgent_tasks WHERE acknowledged = true");

    // Remove bought groceries
    await db.query("DELETE FROM groceries WHERE is_done = true");

    console.log("Daily reset ran ✅");
  } catch (e) {
    console.error("Daily reset failed", e);
  }
}, 60_000);

async function findUserIdByName(name) {
  try {
    const { rows } = await db.query(
      "SELECT id FROM users WHERE LOWER(name) = LOWER($1) ORDER BY id ASC LIMIT 1",
      [name]
    );
    return rows?.[0]?.id ?? null;
  } catch {
    return null;
  }
}

async function createUrgentTask({ title, assigned_to }) {
  const t = typeof title === "string" ? title.trim() : "";
  if (!t) throw new Error("title required");

  const assigned =
    typeof assigned_to === "number" && Number.isFinite(assigned_to) ? assigned_to : null;

  const { rows } = await db.query(
    `
    INSERT INTO urgent_tasks (title, assigned_to)
    VALUES ($1, $2)
    RETURNING *
    `,
    [t, assigned]
  );
  return rows[0];
}
fastify.get("/users", async (request, reply) => {
  try {
    const { rows } = await db.query("SELECT id, name, role, created_at FROM users ORDER BY id");
    const list = rows && rows.length ? rows : [{ id: 1, name: "Admin", role: "admin", created_at: new Date().toISOString() }];
    return reply.send(list);
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});
fastify.get("/", async (request, reply) => {
  try {
    return reply.send({ ok: true, status: "Smart Home Hub backend running" });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.get("/health", async () => {
  return { ok: true };
});

// ---- Today's Tasks (in-memory, unified schema) ----
// Schema: { id, title, date (YYYY-MM-DD), startTime, endTime (ISO), durationMinutes, status: "pending"|"completed", category, gatheringId?, isAutoGenerated }
// Legacy compat: scheduledTime → date/startTime/endTime; completed → status
const TASK_TIME_WINDOWS = { morning: { start: "08:00", end: "12:00" }, afternoon: { start: "12:00", end: "17:00" }, evening: { start: "17:00", end: "22:00" } };
const taskStore = [];

function nextId() {
  return (typeof crypto !== "undefined" && crypto.randomUUID) ? crypto.randomUUID() : `t-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

function toNormalizedTask(raw) {
  if (raw.date && (raw.startTime || raw.scheduledTime)) {
    const start = raw.startTime || raw.scheduledTime;
    const end = raw.endTime || (raw.durationMinutes ? new Date(new Date(start).getTime() + raw.durationMinutes * 60 * 1000).toISOString() : new Date(new Date(start).getTime() + 60 * 60 * 1000).toISOString());
    return {
      id: raw.id,
      title: raw.title,
      date: raw.date,
      startTime: typeof start === "string" ? start : new Date(start).toISOString(),
      endTime: typeof end === "string" ? end : new Date(end).toISOString(),
      durationMinutes: raw.durationMinutes ?? Math.round((new Date(end) - new Date(start)) / 60000),
      status: raw.status ?? (raw.completed ? "completed" : "pending"),
      category: raw.category ?? "general",
      gatheringId: raw.gatheringId ?? null,
      isAutoGenerated: Boolean(raw.isAutoGenerated),
    };
  }
  const scheduled = raw.scheduledTime || raw.startTime;
  if (!scheduled) return null;
  const d = new Date(scheduled);
  const dateStr = d.toISOString().slice(0, 10);
  const dur = raw.durationMinutes ?? 60;
  const endDate = new Date(d.getTime() + dur * 60 * 1000);
  return {
    id: raw.id,
    title: raw.title,
    date: dateStr,
    startTime: d.toISOString(),
    endTime: endDate.toISOString(),
    durationMinutes: dur,
    status: raw.status ?? (raw.completed ? "completed" : "pending"),
    category: raw.category ?? "general",
    gatheringId: raw.gatheringId ?? null,
    isAutoGenerated: Boolean(raw.isAutoGenerated),
  };
}

function timeToMinutes(dateOrIso) {
  const d = new Date(dateOrIso);
  return d.getHours() * 60 + d.getMinutes();
}

function getSlotBounds(dateStr, windowKey) {
  const w = TASK_TIME_WINDOWS[windowKey];
  if (!w) return null;
  const [sh, sm] = w.start.split(":").map(Number);
  const [eh, em] = w.end.split(":").map(Number);
  const start = new Date(`${dateStr}T${String(sh).padStart(2, "0")}:${String(sm).padStart(2, "0")}:00`);
  const end = new Date(`${dateStr}T${String(eh).padStart(2, "0")}:${String(em).padStart(2, "0")}:00`);
  return { start, end };
}

function findNextFreeSlot(taskStoreRef, dateStr, durationMinutes, excludeId) {
  const windows = ["morning", "afternoon", "evening"];
  const dayStart = new Date(`${dateStr}T00:00:00`);
  const tasksOnDay = taskStoreRef
    .filter((t) => t.date === dateStr && t.status !== "completed" && t.id !== excludeId)
    .map(toNormalizedTask)
    .filter(Boolean);
  for (const w of windows) {
    const bounds = getSlotBounds(dateStr, w);
    if (!bounds) continue;
    const slots = [];
    let cursor = bounds.start.getTime();
    const endTs = bounds.end.getTime();
    while (cursor + durationMinutes * 60 * 1000 <= endTs) {
      slots.push({ start: new Date(cursor), end: new Date(cursor + durationMinutes * 60 * 1000) });
      cursor += durationMinutes * 60 * 1000;
    }
    for (const slot of slots) {
      const overlaps = tasksOnDay.some((t) => {
        const tStart = new Date(t.startTime).getTime();
        const tEnd = new Date(t.endTime).getTime();
        return slot.start.getTime() < tEnd && slot.end.getTime() > tStart;
      });
      if (!overlaps) return { startTime: slot.start.toISOString(), endTime: slot.end.toISOString(), date: dateStr };
    }
  }
  return null;
}

function rescheduleMissedTasks(store) {
  const today = new Date().toISOString().slice(0, 10);
  const now = new Date();
  for (const t of store) {
    const norm = toNormalizedTask(t);
    if (!norm || norm.date !== today || norm.status === "completed") continue;
    if (now <= new Date(norm.endTime)) continue;
    const slot = findNextFreeSlot(store, today, norm.durationMinutes, t.id);
    if (slot) {
      t.startTime = slot.startTime;
      t.endTime = slot.endTime;
      t.date = slot.date;
    } else {
      const tomorrow = new Date(now);
      tomorrow.setDate(tomorrow.getDate() + 1);
      const nextDate = tomorrow.toISOString().slice(0, 10);
      const morningSlot = findNextFreeSlot(store, nextDate, norm.durationMinutes, t.id);
      if (morningSlot) {
        t.startTime = morningSlot.startTime;
        t.endTime = morningSlot.endTime;
        t.date = morningSlot.date;
      }
    }
  }
}

fastify.get("/api/tasks", async (request, reply) => {
  rescheduleMissedTasks(taskStore);
  const normalized = taskStore.map(toNormalizedTask).filter(Boolean);
  const sorted = normalized.sort((a, b) => {
    if (a.status === "completed" && b.status !== "completed") return 1;
    if (a.status !== "completed" && b.status === "completed") return -1;
    if (a.date !== b.date) return a.date.localeCompare(b.date);
    const timeA = new Date(a.startTime).getTime();
    const timeB = new Date(b.startTime).getTime();
    if (timeA !== timeB) return timeA - timeB;
    return (a.durationMinutes || 60) - (b.durationMinutes || 60);
  });
  return reply.send({ ok: true, tasks: sorted });
});

fastify.post("/api/tasks", async (request, reply) => {
  const body = request.body || {};
  const title = typeof body.title === "string" ? body.title.trim() : "";
  if (!title) return sendError(reply, 400, "title required");

  let dateStr;
  let startTime;
  let endTime;
  let durationMinutes = body.durationMinutes != null ? Number(body.durationMinutes) : 60;
  const category = typeof body.category === "string" ? body.category : "general";
  const gatheringId = body.gatheringId ?? null;
  const isAutoGenerated = Boolean(body.isAutoGenerated);

  if (body.date && (body.startTime || body.timeWindow)) {
    dateStr = String(body.date).slice(0, 10);
    const window = body.timeWindow && TASK_TIME_WINDOWS[body.timeWindow] ? TASK_TIME_WINDOWS[body.timeWindow] : null;
    const timeStr = body.startTime || (window ? window.start : "09:00");
    if (/^\d{1,2}:\d{2}(:\d{2})?$/.test(String(timeStr))) {
      const normalized = String(timeStr).length === 5 ? `${timeStr}:00` : timeStr;
      startTime = `${dateStr}T${normalized}`;
    } else {
      startTime = new Date(body.startTime).toISOString();
    }
    endTime = body.endTime || new Date(new Date(startTime).getTime() + durationMinutes * 60 * 1000).toISOString();
  } else {
    const scheduledTime = typeof body.scheduledTime === "string" ? body.scheduledTime.trim() : "";
    if (!scheduledTime || isNaN(new Date(scheduledTime).getTime())) return sendError(reply, 400, "scheduledTime or (date + startTime) required");
    const d = new Date(scheduledTime);
    dateStr = d.toISOString().slice(0, 10);
    startTime = d.toISOString();
    endTime = new Date(d.getTime() + durationMinutes * 60 * 1000).toISOString();
  }

  const task = {
    id: nextId(),
    title,
    date: dateStr,
    startTime,
    endTime,
    durationMinutes,
    status: "pending",
    category,
    gatheringId,
    isAutoGenerated,
  };
  taskStore.push(task);
  return reply.code(201).send({ ok: true, task: toNormalizedTask(task) });
});

fastify.patch("/api/tasks/:id", async (request, reply) => {
  const id = request.params?.id;
  if (!id) return sendError(reply, 400, "id required");
  const task = taskStore.find((t) => t.id === id);
  if (!task) return sendError(reply, 404, "task not found");
  const body = request.body || {};
  if (typeof body.title === "string" && body.title.trim()) task.title = body.title.trim();
  if (body.date) task.date = String(body.date).slice(0, 10);
  if (body.startTime) task.startTime = body.startTime;
  if (body.endTime) task.endTime = body.endTime;
  if (body.durationMinutes != null) task.durationMinutes = Number(body.durationMinutes);
  if (body.timeWindow && TASK_TIME_WINDOWS[body.timeWindow]) {
    const bounds = getSlotBounds(task.date, body.timeWindow);
    if (bounds) {
      task.startTime = bounds.start.toISOString();
      task.endTime = new Date(bounds.start.getTime() + (task.durationMinutes || 60) * 60 * 1000).toISOString();
    }
  }
  if (body.status === "pending" || body.status === "completed") {
    task.status = body.status;
    if (task.completed !== undefined) task.completed = body.status === "completed";
  }
  return reply.send({ ok: true, task: toNormalizedTask(task) });
});

fastify.patch("/api/tasks/:id/complete", async (request, reply) => {
  const id = request.params?.id;
  if (!id) return sendError(reply, 400, "id required");
  const task = taskStore.find((t) => t.id === id);
  if (!task) return sendError(reply, 404, "task not found");
  task.status = "completed";
  if (task.completed !== undefined) task.completed = true;
  return reply.send({ ok: true, task: toNormalizedTask(task) });
});

fastify.delete("/api/tasks/:id", async (request, reply) => {
  const id = request.params?.id;
  if (!id) return sendError(reply, 400, "id required");
  const idx = taskStore.findIndex((t) => t.id === id);
  if (idx === -1) return sendError(reply, 404, "task not found");
  taskStore.splice(idx, 1);
  return reply.send({ ok: true });
});

fastify.patch("/api/tasks/reorder", async (request, reply) => {
  const body = request.body || {};
  const items = Array.isArray(body.tasks) ? body.tasks : Array.isArray(body) ? body : [];
  if (items.length === 0) return sendError(reply, 400, "tasks array required");
  for (const item of items) {
    const id = item.id;
    if (!id) continue;
    const task = taskStore.find((t) => t.id === id);
    if (!task) continue;
    if (item.startTime) task.startTime = item.startTime;
    if (item.endTime) task.endTime = item.endTime;
  }
  return reply.send({ ok: true });
});

// ---- Gathering task generation ----
const ROOM_PREP_45 = ["Mariam's Room", "Winklevoss' Room", "Master Bedroom", "Kitchen"];
const ROOM_PREP_60 = ["Dining Room", "TV Room", "Outdoor Seating Area"];
const DRIVEWAY_DURATION = 180;
const OTHER_TASKS = [
  { title: "Buy ingredients for cooking", category: "food", duration: 60 },
  { title: "Check toilet supplies", category: "supplies", duration: 15 },
  { title: "Buy plastic water bottles & soft drinks", category: "supplies", duration: 45 },
  { title: "Move buffet table to designated location", category: "prep", duration: 30 },
  { title: "Prepare nuts & snacks", category: "food", duration: 30 },
  { title: "Prepare tea", category: "hosting", duration: 20 },
  { title: "Prepare Arabic coffee", category: "hosting", duration: 20 },
];

function generateGatheringTasks(payload) {
  const { gatheringType, guestCount, date: eventDateStr, time: eventTimeStr, gatheringId } = payload;
  const eventDate = new Date(`${eventDateStr}T${String(eventTimeStr).slice(0, 5)}:00`);
  const eventDateOnly = eventDateStr.slice(0, 10);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const eventDay = new Date(eventDateOnly);
  eventDay.setHours(0, 0, 0, 0);
  const daysUntil = Math.round((eventDay - today) / (24 * 60 * 60 * 1000));
  const isLunch = gatheringType === "lunch";
  const gateTime = isLunch ? "14:00" : "19:00";
  const gateTask = { title: "Keep the gate open", category: "hosting", duration: 10, time: gateTime, date: eventDateOnly };

  const room45 = ROOM_PREP_45.map((title) => ({ title, duration: 45, category: "room" }));
  const room60 = ROOM_PREP_60.map((title) => ({ title, duration: 60, category: "room" }));
  const driveway = daysUntil >= 7 ? [{ title: "Driveway", category: "room", duration: DRIVEWAY_DURATION }] : [];
  const allRoom = [...room45, ...room60, ...driveway];
  const allOther = [...OTHER_TASKS, gateTask];

  const tasksToPlace = [
    ...allRoom.map((t) => ({ ...t, timeWindow: null })),
    ...allOther.map((t) => ({ ...t, timeWindow: t.time ? null : null, time: t.time, dateOverride: t.date })),
  ];

  const gid = gatheringId || nextId();
  const created = [];
  const windows = ["morning", "afternoon", "evening"];

  function placeTask(taskSpec, dateStr, windowKey) {
    const bounds = getSlotBounds(dateStr, windowKey);
    if (!bounds) return null;
    const dur = taskSpec.duration || 60;
    const existingOnDay = taskStore.filter((t) => t.date === dateStr).map(toNormalizedTask).filter(Boolean);
    let cursor = bounds.start.getTime();
    const endTs = bounds.end.getTime();
    while (cursor + dur * 60 * 1000 <= endTs) {
      const startIso = new Date(cursor).toISOString();
      const endIso = new Date(cursor + dur * 60 * 1000).toISOString();
      const overlaps = existingOnDay.some((t) => {
        const tStart = new Date(t.startTime).getTime();
        const tEnd = new Date(t.endTime).getTime();
        return cursor < tEnd && cursor + dur * 60 * 1000 > tStart;
      });
      if (!overlaps) {
        const task = {
          id: nextId(),
          title: taskSpec.title,
          date: dateStr,
          startTime: startIso,
          endTime: endIso,
          durationMinutes: dur,
          status: "pending",
          category: taskSpec.category || "prep",
          gatheringId: gid,
          isAutoGenerated: true,
        };
        taskStore.push(task);
        created.push(toNormalizedTask(task));
        existingOnDay.push(toNormalizedTask(task));
        return task;
      }
      cursor += dur * 60 * 1000;
    }
    return null;
  }

  if (daysUntil === 1) {
    const todayStr = today.toISOString().slice(0, 10);
    let wi = 0;
    for (const t of allRoom) {
      const w = windows[wi % 3];
      placeTask(t, todayStr, w);
      wi++;
    }
    for (const t of allOther) {
      if (t.dateOverride && t.time) {
        const startIso = `${t.dateOverride}T${t.time}:00`;
        const d = new Date(startIso);
        const endIso = new Date(d.getTime() + (t.duration || 10) * 60 * 1000).toISOString();
        const task = {
          id: nextId(),
          title: t.title,
          date: t.dateOverride,
          startTime: startIso,
          endTime: endIso,
          durationMinutes: t.duration || 10,
          status: "pending",
          category: t.category || "hosting",
          gatheringId: gid,
          isAutoGenerated: true,
        };
        taskStore.push(task);
        created.push(toNormalizedTask(task));
      } else {
        const w = windows[wi % 3];
        placeTask(t, todayStr, w);
        wi++;
      }
    }
  } else if (daysUntil >= 2 && daysUntil <= 6) {
    const prepTasks = [...allRoom, ...allOther.filter((x) => !x.dateOverride)];
    const availableDays = [];
    for (let d = 1; d < daysUntil; d++) {
      const slotDate = new Date(today);
      slotDate.setDate(slotDate.getDate() + d);
      availableDays.push(slotDate.toISOString().slice(0, 10));
    }
    let taskIdx = 0;
    outer: for (const dateStr of availableDays) {
      for (const w of windows) {
        while (taskIdx < prepTasks.length) {
          if (placeTask(prepTasks[taskIdx], dateStr, w)) {
            taskIdx++;
            continue;
          }
          break;
        }
        if (taskIdx >= prepTasks.length) break outer;
      }
    }
    for (const t of allOther) {
      if (t.dateOverride && t.time) {
        const startIso = `${t.dateOverride}T${t.time}:00`;
        const endIso = new Date(new Date(startIso).getTime() + (t.duration || 10) * 60 * 1000).toISOString();
        const task = {
          id: nextId(),
          title: t.title,
          date: t.dateOverride,
          startTime: startIso,
          endTime: endIso,
          durationMinutes: t.duration || 10,
          status: "pending",
          category: t.category || "hosting",
          gatheringId: gid,
          isAutoGenerated: true,
        };
        taskStore.push(task);
        created.push(toNormalizedTask(task));
      }
    }
  } else if (daysUntil >= 7) {
    const prepTasks = [...allRoom, ...allOther.filter((x) => !x.dateOverride)];
    let taskIdx = 0;
    outer7: for (let d = 1; d < daysUntil; d++) {
      const slotDate = new Date(today);
      slotDate.setDate(slotDate.getDate() + d);
      const dateStr = slotDate.toISOString().slice(0, 10);
      for (const w of windows) {
        while (taskIdx < prepTasks.length) {
          if (placeTask(prepTasks[taskIdx], dateStr, w)) {
            taskIdx++;
            continue;
          }
          break;
        }
        if (taskIdx >= prepTasks.length) break outer7;
      }
    }
    for (const t of allOther) {
      if (t.dateOverride && t.time) {
        const startIso = `${t.dateOverride}T${t.time}:00`;
        const endIso = new Date(new Date(startIso).getTime() + (t.duration || 10) * 60 * 1000).toISOString();
        const task = {
          id: nextId(),
          title: t.title,
          date: t.dateOverride,
          startTime: startIso,
          endTime: endIso,
          durationMinutes: t.duration || 10,
          status: "pending",
          category: t.category || "hosting",
          gatheringId: gid,
          isAutoGenerated: true,
        };
        taskStore.push(task);
        created.push(toNormalizedTask(task));
      }
    }
  }

  return { gatheringId: gid, created };
}

fastify.post("/api/gathering/generate", async (request, reply) => {
  try {
    const body = request.body || {};
    const gatheringType = typeof body.gatheringType === "string" ? body.gatheringType : "";
    const validTypes = ["lunch", "dinner", "casual_evening", "other"];
    if (!validTypes.includes(gatheringType)) return sendError(reply, 400, "gatheringType must be one of: lunch, dinner, casual_evening, other");
    const guestCount = Math.max(0, parseInt(String(body.guestCount || 0), 10) || 0);
    const date = typeof body.date === "string" ? body.date.trim().slice(0, 10) : "";
    const time = typeof body.time === "string" ? body.time.trim().slice(0, 5) : "18:00";
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return sendError(reply, 400, "date required (YYYY-MM-DD)");
    const result = generateGatheringTasks({ gatheringType, guestCount, date, time });
    return reply.send({ ok: true, ...result, tasks: result.created });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

// Safe env debug endpoint (no secret values)
fastify.get("/env-status", async () => {
  return {
    ok: true,
    hasOpenAI: Boolean(process.env.OPENAI_API_KEY),
    hasTuya: Boolean(process.env.TUYA_ACCESS_ID && process.env.TUYA_ACCESS_SECRET && process.env.TUYA_ENDPOINT),
    tuyaEndpoint: process.env.TUYA_ENDPOINT || "",
  };
});

async function ensureGroceriesTable() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS groceries (
      id SERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      requested_by TEXT NOT NULL,
      is_done BOOLEAN DEFAULT false,
      created_at TIMESTAMP DEFAULT now()
    );
  `);
}

try {
  await ensureGroceriesTable();
} catch (e) {
  const msg = e instanceof Error ? e.message : String(e);
  console.warn("DB init warning (groceries table):", msg || "connection failed");
}

fastify.get("/weather", async (request, reply) => {
  try {
    // Bahrain (Manama) approx coords
    const lat = 26.2235;
    const lon = 50.5876;
    const controller = new AbortController();
    const t = setTimeout(() => controller.abort(), 5000);
    try {
      const res = await fetch(
        `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code`,
        { signal: controller.signal }
      );
      if (!res.ok) throw new Error(`Weather failed (${res.status})`);
      const data = await res.json().catch(() => null);
      const tempC = Math.round(Number(data?.current?.temperature_2m));
      const code = Number(data?.current?.weather_code);

      // Minimal mapping
      let condition = "Clear";
      let icon = "sun";
      if ([1, 2, 3].includes(code)) {
        condition = "Cloudy";
        icon = "cloud";
      } else if ([45, 48].includes(code)) {
        condition = "Fog";
        icon = "cloud";
      } else if ([51, 53, 55, 61, 63, 65, 80, 81, 82].includes(code)) {
        condition = "Rain";
        icon = "rain";
      }

      return reply.send({ tempC, condition, icon, location: "Bahrain" });
    } finally {
      clearTimeout(t);
    }
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return reply.send({ tempC: 24, condition: "Clear", icon: "sun", location: "Bahrain" });
  }
});

// ---- Groceries ----
fastify.get("/groceries", async (request, reply) => {
  try {
    const { rows } = await db.query("SELECT * FROM groceries ORDER BY id DESC");
    return reply.send(rows);
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.post("/groceries", async (request, reply) => {
  try {
    const body = request.body || {};
    const title = typeof body.name === "string" ? body.name.trim() : typeof body.title === "string" ? body.title.trim() : "";
    const requestedBy = body.requestedBy === "abood" ? "abood" : "family";
    if (!title) return sendError(reply, 400, "Invalid name");
    const { rows } = await db.query(
      "INSERT INTO groceries (title, requested_by) VALUES ($1, $2) RETURNING *",
      [title, requestedBy]
    );
    return reply.send(rows[0]);
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.patch("/groceries/:id", async (request, reply) => {
  try {
    const { id } = request.params;
    const body = request.body || {};
    const bought = body.bought;
    const name = typeof body.name === "string" ? body.name.trim() : typeof body.title === "string" ? body.title.trim() : "";

    const fields = [];
    const values = [];
    let i = 1;

    if (typeof bought === "boolean") {
      fields.push(`is_done = $${i++}`);
      values.push(bought);
    }
    if (name) {
      fields.push(`title = $${i++}`);
      values.push(name);
    }
    if (fields.length === 0) return sendError(reply, 400, "Invalid body");

    values.push(id);
    const { rows } = await db.query(
      `UPDATE groceries SET ${fields.join(", ")} WHERE id = $${i} RETURNING *`,
      values
    );
    if (!rows[0]) return sendError(reply, 404, "Not found");
    return reply.send(rows[0]);
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.delete("/groceries/:id", async (request, reply) => {
  try {
    const { id } = request.params;
    const result = await db.query("DELETE FROM groceries WHERE id = $1 RETURNING id", [id]);
    if (result.rows.length === 0) return sendError(reply, 404, "Not found");
    return reply.send({ ok: true });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.post("/scenes/:sceneId", async (request, reply) => {
  const { sceneId } = request.params;
  const scenes = {
    shower: {
      sceneName: "Shower Mode",
      emoji: "🚿",
      message: "Towel heaters ON for 45 minutes",
      duration_minutes: 45,
    },
    away: {
      sceneName: "Away Mode",
      emoji: "🚪",
      message: "Doors locked • Lights off",
      duration_minutes: null,
    },
    sleep: {
      sceneName: "Sleep Mode",
      emoji: "🌙",
      message: "Lights off • Quiet • AC off",
      duration_minutes: null,
    },
    gathering: {
      sceneName: "Gathering Mode",
      emoji: "🍷",
      message: "Let’s get ready!",
      duration_minutes: null,
    },
  };

  const id = typeof sceneId === "string" ? sceneId : "";
  const s = scenes[id];
  if (!s) {
    return sendError(reply, 400, "Unknown scene");
  }

  // Shower Mode: stub success (devices unknown)
  if (id === "shower") {
    return reply.send({
      ok: true,
      sceneId: id,
      sceneName: s.sceneName,
      emoji: s.emoji,
      message: s.message,
      duration_minutes: s.duration_minutes,
      results: { stub: true },
    });
  }

  // Gathering Mode: no Tuya, create urgent tasks
  if (id === "gathering") {
    const body = request.body || {};
    const gatheringType = body.gatheringType;

    if (gatheringType !== "bahram" && gatheringType !== "haffadh" && gatheringType !== "friends") {
      return sendError(reply, 400, "Invalid gatheringType");
    }

    const aboodId = await findUserIdByName("Abood");
    const titlesByType = {
      bahram: [
        "Prepare living room for Bahram family",
        "Set tea, dates & snacks",
        "Check bathroom supplies",
      ],
      haffadh: [
        "Prepare living room for Haffadh family",
        "Set drinks & snacks",
        "Check bathroom supplies",
      ],
      friends: [
        "Prepare living room for friends",
        "Set drinks & snacks",
        "Check bathroom supplies",
      ],
    };
    const titles = titlesByType[gatheringType];

    const created = [];
    for (const title of titles) {
      try {
        const row = await createUrgentTask({ title, assigned_to: aboodId });
        created.push(row);
      } catch (e) {
        request.log.error({ err: safeErrorMessage(e) }, "error");
      }
    }

    return reply.send({
      ok: true,
      sceneId: id,
      sceneName: s.sceneName,
      emoji: s.emoji,
      message: "Gathering Mode prepared",
      duration_minutes: s.duration_minutes,
      results: { gatheringType, created_urgent_tasks: created },
    });
  }

  // Away/Sleep: real Tuya turn-off
  const awayDeviceIds = [
    "bf764156746c04629ds53u",
    "bf7e312cdc1833bcd1vtwq",
    "bf5267cc9a40db55fdewu1",
  ];
  const sleepExtraDeviceIds = [
    "bf1b3f05e130f44ea0sy5w",
    "bf1cd69a2f640b4d5ewslp",
    "bf6b932ae27f7f2edeycd6",
  ];

  const deviceIds = id === "sleep" ? [...awayDeviceIds, ...sleepExtraDeviceIds] : awayDeviceIds;

  const settled = await Promise.allSettled(deviceIds.map((d) => turnOffIfOn(d)));
  const results = settled.map((r, idx) => {
    const deviceId = deviceIds[idx];
    if (r.status === "fulfilled") return r.value;
    const msg = r.reason instanceof Error ? r.reason.message : "Tuya error";
    return {
      deviceId,
      attempted: true,
      already_off: false,
      turned_off: false,
      offline: false,
      error: String(msg || "Tuya error"),
    };
  });

  const counts = {
    turned_off: results.filter((x) => x.turned_off).length,
    already_off: results.filter((x) => x.already_off).length,
    offline: results.filter((x) => x.offline).length,
    error: results.filter((x) => x.error).length,
  };

  const msgParts = [];
  if (counts.turned_off) msgParts.push(`${counts.turned_off} turned off`);
  if (counts.already_off) msgParts.push(`${counts.already_off} already off`);
  if (counts.offline) msgParts.push(`${counts.offline} offline`);
  if (counts.error) msgParts.push(`${counts.error} error`);
  const message = msgParts.length ? msgParts.join(" • ") : s.message;

  return reply.send({
    ok: true,
    sceneId: id,
    sceneName: s.sceneName,
    emoji: s.emoji,
    message,
    duration_minutes: s.duration_minutes,
    results,
  });
});

// ---- INTEGRATIONS (STUBS) ----
fastify.post("/integrations/tuya/trigger", async (request, reply) => {
  try {
    const body = request.body || {};
    const action = typeof body.action === "string" ? body.action : "";
    const payload = body.payload;

    // TODO: Wire Tuya/SmartLife SDK here (device discovery, scene trigger, etc.)
    return reply.send({ ok: true, action, payload, note: "Tuya integration stub" });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.get("/integrations/tuya/status", async (request, reply) => {
  try {
    return reply.send({
      ok: true,
      connected: false,
      message: "Tuya integration not configured yet",
    });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.post("/integrations/tuya/device/:deviceId/command", async (request, reply) => {
  try {
    const { deviceId } = request.params;
    const body = request.body || {};
    const command = typeof body.command === "string" ? body.command : "";
    const value = body.value;

    // TODO: Send device command via Tuya/SmartLife SDK.
    return reply.send({
      ok: true,
      sent: true,
      deviceId: String(deviceId || ""),
      command,
      value,
    });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

// ---- AI (BACKEND PROXY) ----
fastify.post("/ai/howto", async (request, reply) => {
  try {
    const body = request.body || {};
    const title = body.title;
    const context = body.context;
    const type = body.type;

    if (typeof title !== "string" || !title.trim()) {
      return sendError(reply, 400, "Invalid request");
    }

    const result = await generateHowToAnswer({ title, context, type });
    if (result?.ok === true && typeof result.answer === "string" && result.answer.trim()) {
      return reply.code(200).send({ ok: true, answer: result.answer.trim() });
    }

    const kind =
      result?.error === "OPENAI_NO_CREDITS"
        ? "NO_CREDITS"
        : result?.error === "OPENAI_INVALID_KEY"
          ? "INVALID_KEY"
          : result?.error === "OPENAI_ENV_MISSING"
            ? "ENV_MISSING"
            : "OPENAI_ERROR";
    const detail = typeof result?.detail === "string" && result.detail.trim() ? result.detail.trim() : "OpenAI request failed";
    request.log.error(
      { httpStatus: result?.status ?? null, message: detail, "error.type": result?.type ?? null, "error.code": result?.code ?? null },
      "OpenAI failed"
    );
    return sendError(reply, 500, `${kind}: ${detail}`.slice(0, 200));
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

// GET variant for debugging / quick test
fastify.get("/ai/howto", async (request, reply) => {
  try {
    const { taskTitle, context } = request.query || {};
    const title = typeof taskTitle === "string" ? taskTitle : "";
    const ctx = typeof context === "string" ? context : "";
    if (!title.trim()) return sendError(reply, 400, "Invalid request");

    const result = await generateHowToAnswer({ title, context: ctx, type: "task" });
    if (result?.ok === true && typeof result.answer === "string" && result.answer.trim()) {
      return reply.code(200).send({ ok: true, answer: result.answer.trim() });
    }
    const kind =
      result?.error === "OPENAI_NO_CREDITS"
        ? "NO_CREDITS"
        : result?.error === "OPENAI_INVALID_KEY"
          ? "INVALID_KEY"
          : result?.error === "OPENAI_ENV_MISSING"
            ? "ENV_MISSING"
            : "OPENAI_ERROR";
    const detail = typeof result?.detail === "string" && result.detail.trim() ? result.detail.trim() : "OpenAI request failed";
    request.log.error({ err: detail }, "OpenAI failed");
    return sendError(reply, 500, `${kind}: ${detail}`.slice(0, 200));
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

async function deviceSwitchHandler(request, reply) {
  try {
    const deviceId = request.params?.deviceId;
    const body = request.body && typeof request.body === "object" ? request.body : {};
    const on = body.on;

    if (typeof deviceId !== "string" || !deviceId.trim()) {
      return sendError(reply, 400, "deviceId required");
    }
    if (typeof on !== "boolean") {
      return sendError(reply, 400, "on must be boolean");
    }

    const trimmedId = deviceId.trim();
    request.log.info({ deviceId: trimmedId, on }, "Tuya switch request");

    const tuyaResponse = await setDeviceSwitch(trimmedId, on);
    const sanitized = {
      deviceId: trimmedId,
      ok: Boolean(tuyaResponse?.ok),
      error: typeof tuyaResponse?.error === "string" ? tuyaResponse.error : null,
    };
    request.log.info(sanitized, "Tuya response (sanitized)");

    if (!tuyaResponse || tuyaResponse.ok !== true) {
      const errMsg = typeof tuyaResponse?.error === "string" ? tuyaResponse.error : "Tuya command failed";
      return sendError(reply, 500, errMsg);
    }

    return reply.send({ ok: true, deviceId: trimmedId, on, tuyaResponse });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
}
fastify.get("/devices", async (request, reply) => {
  try {
    const devices = await getDevices();
    const raw = (process.env.TUYA_DEVICE_IDS || "").trim();
    const allowIds = raw ? raw.split(",").map((x) => String(x).trim()).filter(Boolean) : [];
    const filtered = allowIds.length ? devices.filter((d) => d && allowIds.includes(d.id)) : devices;
    return reply.send({ ok: true, devices: filtered });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});
fastify.post("/devices/:deviceId/toggle", deviceSwitchHandler);
fastify.post("/devices/:deviceId/switch", deviceSwitchHandler);

// ---- Daily Tasks (staff, time windows + recurrence) ----
const TIME_REGEX = /^([01]?\d|2[0-3]):([0-5]\d)(?::([0-5]\d))?$/;
const DATE_REGEX = /^\d{4}-\d{2}-\d{2}$/;
function validTime(s) {
  return typeof s === "string" && TIME_REGEX.test(s.trim());
}
function validDate(s) {
  return typeof s === "string" && DATE_REGEX.test(s.trim()) && !isNaN(new Date(s + "T12:00:00Z").getTime());
}
function validRecurrence(s) {
  return s === "none" || s === "daily" || s === "weekly";
}

fastify.get("/daily-tasks", async (request, reply) => {
  try {
    const staffUserId = request.query?.staff_user_id;
    const date = request.query?.date;
    if (!staffUserId || !Number.isInteger(Number(staffUserId))) {
      return sendError(reply, 400, "staff_user_id required (integer)");
    }
    const dateStr = date && validDate(date) ? date.trim() : new Date().toISOString().slice(0, 10);
    const result = await dailyTasksDb.getTasksWithInstances(db, Number(staffUserId), dateStr);
    return reply.send({ ok: true, ...result });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.post("/daily-tasks", async (request, reply) => {
  try {
    const body = request.body || {};
    const staff_user_id = body.staff_user_id;
    const title = typeof body.title === "string" ? body.title.trim() : "";
    const notes = typeof body.notes === "string" ? body.notes.trim() : "";
    const window_start = body.window_start;
    const window_end = body.window_end;
    const timezone = typeof body.timezone === "string" ? body.timezone.trim() || "Asia/Bahrain" : "Asia/Bahrain";
    const recurrence = validRecurrence(body.recurrence) ? body.recurrence : "none";
    let recurrence_days = body.recurrence_days;
    const start_date = body.start_date;
    const end_date = body.end_date;

    if (!staff_user_id || !Number.isInteger(Number(staff_user_id))) {
      return sendError(reply, 400, "staff_user_id required (integer)");
    }
    if (!title) return sendError(reply, 400, "title required");
    if (!validTime(window_start)) return sendError(reply, 400, "window_start required (HH:MM or HH:MM:SS)");
    if (!validTime(window_end)) return sendError(reply, 400, "window_end required (HH:MM or HH:MM:SS)");
    if (!validDate(start_date)) return sendError(reply, 400, "start_date required (YYYY-MM-DD)");

    if (recurrence === "weekly" && Array.isArray(recurrence_days)) {
      recurrence_days = recurrence_days.filter((d) => Number.isInteger(d) && d >= 0 && d <= 6);
    } else {
      recurrence_days = null;
    }
    const endDateVal = end_date && validDate(end_date) ? end_date.trim() : null;

    const row = await dailyTasksDb.createDailyTask(db, {
      staff_user_id: Number(staff_user_id),
      title,
      notes,
      window_start: String(window_start).trim(),
      window_end: String(window_end).trim(),
      timezone,
      recurrence,
      recurrence_days,
      start_date: String(start_date).trim(),
      end_date: endDateVal,
    });
    return reply.code(201).send({ ok: true, data: row });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.patch("/daily-tasks/:id", async (request, reply) => {
  try {
    const id = request.params?.id;
    if (!id || !Number.isInteger(Number(id))) return sendError(reply, 400, "id required");
    const body = request.body || {};
    const payload = {};
    if (typeof body.title === "string" && body.title.trim()) payload.title = body.title.trim();
    if (typeof body.notes === "string") payload.notes = body.notes.trim();
    if (validTime(body.window_start)) payload.window_start = String(body.window_start).trim();
    if (validTime(body.window_end)) payload.window_end = String(body.window_end).trim();
    if (typeof body.timezone === "string") payload.timezone = body.timezone.trim() || "Asia/Bahrain";
    if (validRecurrence(body.recurrence)) payload.recurrence = body.recurrence;
    if (Array.isArray(body.recurrence_days)) {
      payload.recurrence_days = body.recurrence_days.filter((d) => Number.isInteger(Number(d)) && Number(d) >= 0 && Number(d) <= 6);
    }
    if (validDate(body.start_date)) payload.start_date = body.start_date.trim();
    if (body.end_date !== undefined) payload.end_date = body.end_date && validDate(body.end_date) ? body.end_date.trim() : null;
    if (typeof body.is_active === "boolean") payload.is_active = body.is_active;

    const row = await dailyTasksDb.updateDailyTask(db, Number(id), payload);
    if (!row) return sendError(reply, 404, "Task not found");
    return reply.send({ ok: true, data: row });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.post("/daily-tasks/:id/complete", async (request, reply) => {
  try {
    const id = request.params?.id;
    const date = request.body?.date ?? request.query?.date ?? new Date().toISOString().slice(0, 10);
    if (!id || !Number.isInteger(Number(id))) return sendError(reply, 400, "id required");
    if (!validDate(date)) return sendError(reply, 400, "date required (YYYY-MM-DD)");
    const instance = await dailyTasksDb.completeInstance(db, Number(id), date.trim());
    if (!instance) return sendError(reply, 404, "Task not found");
    return reply.send({ ok: true, data: instance });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.post("/daily-tasks/:id/skip", async (request, reply) => {
  try {
    const id = request.params?.id;
    const date = request.body?.date ?? request.query?.date ?? new Date().toISOString().slice(0, 10);
    if (!id || !Number.isInteger(Number(id))) return sendError(reply, 400, "id required");
    if (!validDate(date)) return sendError(reply, 400, "date required (YYYY-MM-DD)");
    const instance = await dailyTasksDb.skipInstance(db, Number(id), date.trim());
    if (!instance) return sendError(reply, 404, "Task not found");
    return reply.send({ ok: true, data: instance });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

// ---- TUYA (PHASE 1 REAL CLIENT) ----
// (Deprecated) older /tuya routes removed in favor of /devices
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

await fastify.register(fastifyStatic, {
  root: __dirname,
})


// ---- USERS ----

fastify.post('/users', async (request) => {
    const { name, role } = request.body
    console.log("User created ✅", { name, role });
    const { rows } = await db.query(
      'INSERT INTO users (name, role) VALUES ($1, $2) RETURNING *',
      [name, role]
    )
  
    return rows[0]
  })
// ---- TASKS ----

fastify.post('/tasks', async (request) => {
    const { title, assigned_to, day_of_week } = request.body
  
    const { rows } = await db.query(
      `INSERT INTO tasks (title, assigned_to, day_of_week)
       VALUES ($1, $2, $3)
       RETURNING *`,
      [title, assigned_to, day_of_week]
    )
  
    return rows[0]
  })
  fastify.get('/tasks/today/:userId', async (request) => {
    const { userId } = request.params
    const today = new Date().getDay()
  
    const { rows } = await db.query(
      'SELECT * FROM tasks WHERE assigned_to = $1 AND day_of_week = $2',
      [userId, today]
    )
  
    return rows
  })
  fastify.get('/tasks/assigned/:userId', async (request) => {
    const { userId } = request.params
  
    const { rows } = await db.query(
      'SELECT * FROM tasks WHERE assigned_to = $1 ORDER BY id DESC',
      [userId]
    )
  
    return rows
  })
  fastify.get('/tasks', async () => {
    const { rows } = await db.query('SELECT * FROM tasks ORDER BY id DESC')
    return rows
  })
  // ---- URGENT TASKS ----

// Create urgent task
fastify.post("/urgent_tasks", async (request, reply) => {
  try {
    const body = request.body || {};
    const title = body.title;
    let assigned_to = body.assigned_to;
    const assigned_to_name = body.assigned_to_name;

    if ((assigned_to == null || assigned_to === "") && typeof assigned_to_name === "string" && assigned_to_name.trim()) {
      assigned_to = await findUserIdByName(assigned_to_name.trim());
    }
    const row = await createUrgentTask({ title, assigned_to });
    return reply.send(row);
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 400, "Invalid urgent task");
  }
});
// GET all urgent tasks
fastify.get("/urgent_tasks", async () => {
  const { rows } = await db.query(
    "SELECT * FROM urgent_tasks ORDER BY id DESC"
  );
  return rows;
});

// Get urgent tasks by user
fastify.get('/urgent_tasks/:userId', async (request) => {
  const { userId } = request.params

  const { rows } = await db.query(
    `
    SELECT * FROM urgent_tasks
    WHERE assigned_to = $1
    ORDER BY id DESC
    `,
    [userId]
  )

  return rows
})
// Get today's tasks
fastify.get("/tasks/today", async (request, reply) => {
  const today = new Date();
  const day = today.getDay(); // 0=Sun, 1=Mon, ... 6=Sat

  const { rows } = await db.query(
    "SELECT * FROM tasks WHERE day_of_week = $1 ORDER BY id DESC",
    [day]
  );

  return rows;
});
// Acknowledge urgent task
fastify.patch('/urgent_tasks/:id/ack', async (request) => {
  const { id } = request.params

  const { rows } = await db.query(
    `
    UPDATE urgent_tasks
    SET acknowledged = true
    WHERE id = $1
    RETURNING *
    `,
    [id]
  )

  return rows[0]
})
fastify.get('/today/:userId', async (request) => {
  const { userId } = request.params
  const today = new Date().getDay()

  const urgent = await db.query(
    `SELECT * FROM urgent_tasks
     WHERE assigned_to = $1 AND acknowledged = false
     ORDER BY id DESC`,
    [userId]
  )

  const normal = await db.query(
    `SELECT * FROM tasks
     WHERE assigned_to = $1 AND day_of_week = $2
     ORDER BY id DESC`,
    [userId, today]
  )

  return {
    urgent: urgent.rows,
    tasks: normal.rows,
  }
})
fastify.patch("/urgent_tasks/:id", async (request, reply) => {
  try {
    const { id } = request.params;
    const body = request.body || {};

    const fields = [];
    const values = [];
    let i = 1;

    if (typeof body.acknowledged === "boolean") {
      fields.push(`acknowledged = $${i++}`);
      values.push(body.acknowledged);
    }
    if (typeof body.title === "string" && body.title.trim()) {
      fields.push(`title = $${i++}`);
      values.push(body.title.trim());
    }

    if (fields.length === 0) {
      return sendError(reply, 400, "Invalid body");
    }

    values.push(id);
    const { rows } = await db.query(
      `UPDATE urgent_tasks SET ${fields.join(", ")} WHERE id = $${i} RETURNING *`,
      values
    );
    if (!rows[0]) return sendError(reply, 404, "Urgent task not found");
    return reply.send(rows[0]);
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});
fastify.patch("/tasks/:taskId/toggle", async (request, reply) => {
  const { taskId } = request.params;

  const result = await db.query(
    `
    UPDATE tasks
    SET is_done = NOT is_done
    WHERE id = $1
    RETURNING *
    `,
    [taskId]
  );

  if (result.rows.length === 0) {
    return sendError(reply, 404, "Task not found");
  }

  return reply.send(result.rows[0]);
});

// Match frontend PATCH /tasks/:id usage
fastify.patch("/tasks/:id", async (request, reply) => {
  try {
    const { id } = request.params;
    const body = request.body || {};
    const fields = [];
    const values = [];
    let i = 1;

    if (typeof body.is_done === "boolean") {
      fields.push(`is_done = $${i++}`);
      values.push(body.is_done);
    }
    if (typeof body.title === "string" && body.title.trim()) {
      fields.push(`title = $${i++}`);
      values.push(body.title.trim());
    }

    if (fields.length === 0) {
      return sendError(reply, 400, "Invalid body");
    }

    values.push(id);
    const result = await db.query(
      `UPDATE tasks SET ${fields.join(", ")} WHERE id = $${i} RETURNING *`,
      values
    );

    if (result.rows.length === 0) return sendError(reply, 404, "Task not found");
    return reply.send(result.rows[0]);
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.delete("/tasks/:id", async (request, reply) => {
  try {
    const { id } = request.params;
    const result = await db.query("DELETE FROM tasks WHERE id = $1 RETURNING id", [id]);
    if (result.rows.length === 0) return sendError(reply, 404, "Task not found");
    return reply.send({ ok: true });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

fastify.delete("/urgent_tasks/:id", async (request, reply) => {
  try {
    const { id } = request.params;
    const result = await db.query("DELETE FROM urgent_tasks WHERE id = $1 RETURNING id", [id]);
    if (result.rows.length === 0) return sendError(reply, 404, "Urgent task not found");
    return reply.send({ ok: true });
  } catch (e) {
    request.log.error({ err: safeErrorMessage(e) }, "error");
    return sendError(reply, 500, safeErrorMessage(e));
  }
});

// ---- Global error handler: never expose stack ----
fastify.setErrorHandler((error, request, reply) => {
  const msg = safeErrorMessage(error);
  request.log.error({ err: msg }, "error");
  return sendError(reply, 500, msg);
});

// ---- Graceful shutdown ----
async function shutdown(signal) {
  console.log(`${signal} received, shutting down gracefully`);
  try {
    await fastify.close();
    await db.end();
    console.log("Shutdown complete");
    process.exit(0);
  } catch (e) {
    console.error("Shutdown error:", safeErrorMessage(e));
    process.exit(1);
  }
}
process.on("SIGINT", () => shutdown("SIGINT"));
process.on("SIGTERM", () => shutdown("SIGTERM"));

const port = Number(process.env.PORT) || 3001;
fastify.listen({ port }, (err) => {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
  console.log(`Server running on http://localhost:${port}`);
});
