import { NextResponse } from "next/server";
import { getDb } from "@/lib/server/db";
import {
  authenticateRequest,
  isAuthError,
  parseBody,
  errorResponse,
  getActor,
} from "@/lib/server/middleware";
import { logActivity } from "@/lib/server/activityLog";

/**
 * PATCH /api/tasks/[id]
 * Update fields on a scheduled task.
 */
export async function PATCH(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const auth = authenticateRequest(request);
  if (isAuthError(auth)) return auth;

  try {
    const { id } = await params;
    const body = await parseBody(request);

    const patch: Record<string, unknown> = {};
    if (body.title !== undefined) patch.title = String(body.title);
    if (body.date !== undefined) patch.date = String(body.date);
    if (body.startTime !== undefined) patch.start_time = body.startTime;
    if (body.endTime !== undefined) patch.end_time = body.endTime;
    if (body.durationMinutes !== undefined) patch.duration_minutes = Number(body.durationMinutes);
    if (body.status !== undefined) patch.status = String(body.status);
    if (body.category !== undefined) patch.category = String(body.category);
    if (body.gatheringId !== undefined) patch.gathering_id = body.gatheringId ? String(body.gatheringId) : null;
    if (body.isAutoGenerated !== undefined) patch.is_auto_generated = body.isAutoGenerated === true;
    if (body.assignedBy !== undefined) patch.assigned_by = body.assignedBy ? String(body.assignedBy) : null;
    if (body.room !== undefined) patch.room = body.room ? String(body.room) : null;

    if (Object.keys(patch).length === 0) {
      return errorResponse(400, "No fields to update");
    }

    const db = getDb();
    const { data, error } = await db
      .from("scheduled_tasks")
      .update(patch)
      .eq("id", id)
      .select()
      .single();

    if (error) throw error;
    if (!data) return errorResponse(404, "Task not found");

    const task = {
      id: data.id,
      title: data.title,
      date: data.date,
      startTime: data.start_time,
      endTime: data.end_time,
      durationMinutes: data.duration_minutes,
      status: data.status,
      category: data.category,
      gatheringId: data.gathering_id,
      isAutoGenerated: data.is_auto_generated,
      assignedBy: data.assigned_by,
      room: data.room,
    };

    const actor = getActor(request, body);
    await logActivity({
      ...actor,
      action: "task_update",
      entity_type: "scheduled_task",
      entity_id: id,
      payload_json: patch,
    });

    return NextResponse.json({ ok: true, task });
  } catch (err) {
    return errorResponse(500, (err as Error).message);
  }
}

/**
 * DELETE /api/tasks/[id]
 * Delete a scheduled task.
 */
export async function DELETE(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const auth = authenticateRequest(request);
  if (isAuthError(auth)) return auth;

  try {
    const { id } = await params;

    const db = getDb();
    const { error } = await db
      .from("scheduled_tasks")
      .delete()
      .eq("id", id);

    if (error) throw error;

    const actor = getActor(request);
    await logActivity({
      ...actor,
      action: "task_delete",
      entity_type: "scheduled_task",
      entity_id: id,
    });

    return NextResponse.json({ ok: true });
  } catch (err) {
    return errorResponse(500, (err as Error).message);
  }
}
