import { NextResponse } from "next/server";
import { getDb } from "@/lib/server/db";
import {
  authenticateRequest,
  isAuthError,
  parseBody,
  errorResponse,
  getActor,
} from "@/lib/server/middleware";
import { logActivity } from "@/lib/server/activityLog";

/**
 * PATCH /api/tasks/[id]/complete
 * Mark a task as completed and check for urgent tasks with alert_on_free.
 */
export async function PATCH(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const auth = authenticateRequest(request);
  if (isAuthError(auth)) return auth;

  try {
    const { id } = await params;
    const body = await parseBody(request);
    const db = getDb();

    // Mark task as completed
    const { data, error } = await db
      .from("scheduled_tasks")
      .update({ status: "completed" })
      .eq("id", id)
      .select()
      .single();

    if (error) throw error;
    if (!data) return errorResponse(404, "Task not found");

    // Check for urgent tasks with alert_on_free=true and acknowledged=false
    const { data: urgentTasks } = await db
      .from("urgent_tasks")
      .select("id")
      .eq("alert_on_free", true)
      .eq("acknowledged", false);

    if (urgentTasks && urgentTasks.length > 0) {
      const urgentIds = urgentTasks.map((u: { id: string }) => u.id);
      await db
        .from("urgent_tasks")
        .update({ alert_on_free: false })
        .in("id", urgentIds);
    }

    const task = {
      id: data.id,
      title: data.title,
      date: data.date,
      startTime: data.start_time,
      endTime: data.end_time,
      durationMinutes: data.duration_minutes,
      status: data.status,
      category: data.category,
      gatheringId: data.gathering_id,
      isAutoGenerated: data.is_auto_generated,
      assignedBy: data.assigned_by,
      room: data.room,
    };

    const actor = getActor(request, body);
    await logActivity({
      ...actor,
      action: "task_complete",
      entity_type: "scheduled_task",
      entity_id: id,
      payload_json: { title: data.title },
    });

    return NextResponse.json({ ok: true, task });
  } catch (err) {
    return errorResponse(500, (err as Error).message);
  }
}
