import type { TaskRow } from "../services/tasks";

export type UITask = {
  id: string;
  title: string;
  date: string;
  startTime: string;
  endTime: string;
  durationMinutes: number;
  status: "pending" | "completed";
  category?: string;
  gatheringId?: string | null;
  isAutoGenerated?: boolean;
  urgent?: boolean;
  room?: string | null;
  assignedBy?: string | null;
};

const TIME_WINDOW_STARTS: Record<string, { h: number; m: number }> = {
  morning: { h: 8, m: 0 },
  afternoon: { h: 12, m: 0 },
  evening: { h: 17, m: 0 },
};

export function taskRowToUI(row: TaskRow): UITask {
  const date = row.start_time.slice(0, 10);
  return {
    id: row.id,
    title: row.title,
    date,
    startTime: row.start_time,
    endTime: row.end_time,
    durationMinutes: row.duration ?? 60,
    status: row.status,
    category: row.category ?? undefined,
    gatheringId: row.gathering_id ?? null,
    isAutoGenerated: row.is_auto_generated ?? undefined,
    urgent: row.urgent ?? false,
    room: row.room ?? null,
    assignedBy: row.assigned_by ?? null,
  };
}

export function taskRowsToUI(rows: TaskRow[]): UITask[] {
  return rows.map(taskRowToUI);
}

/** Build start_time and end_time from date, time window, and duration (for create). */
export function timeWindowToStartEnd(
  date: string,
  timeWindow: string,
  durationMinutes: number
): { start_time: string; end_time: string } {
  const start = TIME_WINDOW_STARTS[timeWindow] ?? TIME_WINDOW_STARTS.morning;
  const startDate = new Date(`${date}T${String(start.h).padStart(2, "0")}:${String(start.m).padStart(2, "0")}:00`);
  const endDate = new Date(startDate.getTime() + durationMinutes * 60 * 1000);
  return {
    start_time: startDate.toISOString(),
    end_time: endDate.toISOString(),
  };
}
