export const DISHES: readonly string[] = [
  "Lasagna",
  "Pasta with mushroom sauce",
  "Spaghetti",
  "Noodles",
  "Mushroom soup",
  "Vegetable soup",
  "Pumpkin soup",
  "Machboos rubyan",
  "Rubyan 9aloona with white rice",
  "Kofta with white rice",
  "Biryani beef",
  "Biryani chicken",
  "Mendi chicken",
  "Mujadara",
  "Saffron chicken",
  "Chicken tikka with green sauce and mashed potatoes",
  "Mushroom chicken with mashed potatoes",
  "Chinese chicken",
  "Chicken makhani",
  "Chicken dopiyaza",
  "Charcoal chicken",
  "Chicken pizza",
  "Chicken burger (Nawaf recipe)",
  "Bamiya beef",
  "Minced meat with vegetables",
  "Kofta with hummus",
  "Kufta",
  "Roasted rubyan (Cajun)",
  "Rubyan dopiyaza",
  "Rubyan with cream sauce",
  "Qaliya rubyan",
  "Salmon",
  "Supreme fish",
  "Khoresh sabzy",
  "Halloumi in tomato sauce",
  "Dahl",
  "Musaka'a with eggplant",
  "Vegetable pizza",
  "Margarita pizza",
  "Fetah with hummus",
  "Labneh sandwich",
];
