import { NextResponse } from "next/server";
import { getDb } from "@/lib/server/db";
import {
  authenticateRequest,
  isAuthError,
  parseBody,
  errorResponse,
  getActor,
} from "@/lib/server/middleware";
import { logActivity } from "@/lib/server/activityLog";

/**
 * GET /api/tasks
 * List all scheduled tasks ordered by date, start_time.
 */
export async function GET(request: Request) {
  const auth = authenticateRequest(request);
  if (isAuthError(auth)) return auth;

  try {
    const db = getDb();
    const { data, error } = await db
      .from("scheduled_tasks")
      .select("*")
      .order("date", { ascending: true })
      .order("start_time", { ascending: true });

    if (error) throw error;

    const tasks = (data || []).map((row: Record<string, unknown>) => ({
      id: row.id,
      title: row.title,
      date: row.date,
      startTime: row.start_time,
      endTime: row.end_time,
      durationMinutes: row.duration_minutes,
      status: row.status,
      category: row.category,
      gatheringId: row.gathering_id,
      isAutoGenerated: row.is_auto_generated,
      assignedBy: row.assigned_by,
      room: row.room,
    }));

    return NextResponse.json({ ok: true, tasks });
  } catch (err) {
    return errorResponse(500, (err as Error).message);
  }
}

/**
 * POST /api/tasks
 * Create a new scheduled task.
 */
export async function POST(request: Request) {
  const auth = authenticateRequest(request);
  if (isAuthError(auth)) return auth;

  try {
    const body = await parseBody(request);
    const id = crypto.randomUUID();

    const row = {
      id,
      title: body.title ? String(body.title) : null,
      date: body.date ? String(body.date) : null,
      start_time: body.startTime ?? body.scheduledTime ?? null,
      end_time: body.endTime ?? null,
      duration_minutes: body.durationMinutes != null ? Number(body.durationMinutes) : null,
      status: "pending",
      category: body.category ? String(body.category) : null,
      gathering_id: body.gatheringId ? String(body.gatheringId) : null,
      is_auto_generated: body.isAutoGenerated === true,
      assigned_by: body.assignedBy ? String(body.assignedBy) : null,
      room: body.room ? String(body.room) : null,
    };

    const db = getDb();
    const { data, error } = await db
      .from("scheduled_tasks")
      .insert(row)
      .select()
      .single();

    if (error) throw error;

    const task = {
      id: data.id,
      title: data.title,
      date: data.date,
      startTime: data.start_time,
      endTime: data.end_time,
      durationMinutes: data.duration_minutes,
      status: data.status,
      category: data.category,
      gatheringId: data.gathering_id,
      isAutoGenerated: data.is_auto_generated,
      assignedBy: data.assigned_by,
      room: data.room,
    };

    const actor = getActor(request, body);
    await logActivity({
      ...actor,
      action: "task_create",
      entity_type: "scheduled_task",
      entity_id: id,
      payload_json: task,
    });

    return NextResponse.json({ ok: true, task }, { status: 201 });
  } catch (err) {
    return errorResponse(500, (err as Error).message);
  }
}
